### DISCUSSION TITLE
How to use template in response for number type?

### DISCUSSION THREAD

**Discussion by akadnikov** [microcks/microcks#1050] [Q&A] [answered]
Hi!
In example Pastries API we have PUT request
<img width="1498" alt="image" src="https://github.com/microcks/microcks/assets/14162992/0b2b2bf4-ed2e-4ace-b27e-63090fa7eaf4">

with body {"price":2.6}
I'm trying to template response with price value "price":"{{ request.body/price }}"
but in response from mock I get
 
{
    "name": "Eclair Cafe",
    "description": "Delicieux Eclair au Cafe pas calorique du tout",
    "size": "M",
    "price": "2.8",
    "status": "available"
}

expected  "price": 2.8 (number, not string)

**Comment by lbroudoux** [comment, marked as answer]
Hello!
For using the number type, you have to serialize your example differently to avoid Microcks interpreting it as a String.
Typically, IIRC, you have to use the serialized JSON form embedded in YAML.  Something like:

```yaml
examples:
  MOCK_0:
    value: |-
      {"name": "Eclair Cafe", "description": "Delicieux Eclair au Cafe pas calorique du tout", "size": "M", "price": {{request.body/price}}, "status": "available"}
```
that way, the example is considered as a String and not as JSON with type interpolation.

Let me know if those memories are correct.
