### DISCUSSION TITLE
Specific delays per example

### DISCUSSION THREAD

**Discussion by Apoorva64** [microcks/microcks#1092] [Ideas]
In a front-end application, requests to the same API endpoint may exhibit different processing times.

Depending on the duration of these requests, a dynamic display of a spinner or direct rendering of the content is determined. 

To facilitate testing and development, a mocked API endpoint is needed, providing responses with varying response times.

We already have an implementation of "Delays" in Microcks but it is per "endpoint+verb".
To add this feature we could add to the "Response" object a delay that is specific to it.
To import the data we could add "OpenAPI Extensions" such as "x-microcks-example" which would be placed at the exemple level and contain   the "delay" in the form of a variable.

```yaml
                examples:
                  laurent_cars:
                    value:
                      [
                          {"name": "307", "model": "Peugeot 307", "year": 2003},
                          {"name": "jean-pierre", "model": "Peugeot Traveler", "year": 2017}
                      ]
                    x-microcks-example:
                      delay: 1000
```
- when a delay is found in the example level  use that delay (x-microcks-example)
- else use the delay found at the verb/operation level (x-microcks-operation)
- else don't use a delay and make the request as fast as possible
