### DISCUSSION TITLE
Certification issue after MicrocksInstall patching

### DISCUSSION THREAD

**Discussion by vijia123** [microcks/microcks#1230] [Q&A]
We recently patched MicrocksInstall to version 1.9.0 to make it compatible with Microcks Operator 1.9.0 in Openshift to address a vulnerability. However, when we tried to sign into microcks console after the patching, we got a blank white screen. (But we can see there is a new session in microcks keycloak that has been created when trying to sign in) Also we found out there are some error logs from microcks pod, which seem related to certificate issue:

`JwtDecoderInitializationException: Failed to lazily resolve the supplied JwtDecoder instance`
` IllegalArgumentException: Unable to resolve the Configuration with the provided Issuer of “https://microcks-keycloak-microcks.apps.../realms/microcks”`
`ResourceAccessException: I/O error on GET request for “https://microcks-keycloak-microcks.apps.../realms/microcks/.well-known/openid-configuration”: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`
`SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`
`ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`
`SunCertPathBuilderException: unable to find valid certification path to requested target`

How can we resolve this certification issue? How to allow the certificates with the specific issuer for microcks in openshift?

Thank you!

**Comment by lbroudoux** [comment]
Hi @vijia123 

We've switched the security provider with Microcks 1.8.0, and depending on your Keycloak configuration, you may encounter this issue
because the connection between main pod and Kecyloak now performs validation.

I think that in your case, you may have 2 things to check:
1. Be certain to specify a `keycloak.privateUrl` in your Custom Resource so that JWT tokens are trusted using this direct URL,
2. If the previous point does not solve the issue, you may need to mount an additional secret into the main Webapp pod to provide a truststore with keycloak certificates.

Point 2 can be done that way:
* Specifiy `microcks.customSecretRef` in your CR.
```yaml
spec:
  microcks:
    customSecretRef:
       secret: microcks-keystore
       key: cacerts
```
* Add `JAVA_OPTIONS` to env variables like this so that JVM will have the password to access the truststore:
```yaml
spec:
  microcks:
    env:
      - name: JAVA_OPTIONS
        value: "-Djavax.net.ssl.trustStore=/deployments/config/custom/secret/cacerts -Djavax.net.ssl.trustStorePassword=XXXXX"
```

Let us know how things are going.
