### DISCUSSION TITLE
Issue with Keycloak PostgreSQL Pod Permission Error on OpenShift using Microcks Operator

### DISCUSSION THREAD

**Discussion by knighthl** [microcks/microcks#1266] [Q&A] [answered]
Hi Microcks team,

I've encountered a permission issue when deploying Microcks using the Microcks Operator on OpenShift. Specifically, the error occurs in the my-microcksinstall-keycloak-postgresql pod during the initialization process.

Error Details:
```
chmod: /var/lib/postgresql/data: Operation not permitted
chmod: /var/run/postgresql: Operation not permitted
The files belonging to this database system will be owned by user "1000730000".
This user must also own the server process.
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
Data page checksums are disabled.
fixing permissions on existing directory /var/lib/postgresql/data ... initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
```
CRD Configuration:

```
apiVersion: microcks.github.io/v1alpha1
kind: MicrocksInstall
metadata:
  name: my-microcksinstall
spec:
  name: my-microcksinstall
  version: 1.10.0
  microcks:
    replicas: 1
  postman:
    replicas: 1
  keycloak:
    install: true
    persistent: true
    volumeSize: 1Gi
  mongodb:
    install: true
    persistent: true
    volumeSize: 2Gi
```
**Environment**:
OpenShift Version: 4.14
Microcks Operator Version: 1.10.0

**Questions**:
Is this a known issue with the Microcks Operator on OpenShift, particularly with the Keycloak PostgreSQL pod?
Are there recommended configurations or workarounds to prevent this permission error from occurring?

Any guidance or suggestions would be greatly appreciated.

Thanks!
