### DISCUSSION TITLE
Need help understanding why in websocket the endpoint for `receive` operation also broadcasts messages

### DISCUSSION THREAD

**Discussion by derberg** [microcks/microcks#1566] [Q&A]
This is my websocket document with one `send` and one `receive` operation.

```yml
asyncapi: 3.0.0
defaultContentType: text/plain
info:
  title: Hoppscotch WebSocket Server
  version: 1.0.0
  description: >
    This document is purely for mocking the official Hoppscotch Websocket Echo server.

servers:
  echoServer:
    host: echo-websocket.hoppscotch.io
    protocol: wss

channels:
  echo:
    description: >
      The single channel where messages are sent to and echoed back. Echo server also regularly drops a timestampl to that channel.
    address: /
    messages:
      echo:
        $ref: '#/components/messages/echo'
      timestamp:
        $ref: '#/components/messages/timestamp'
    bindings:
      ws:
        method: POST

operations:
  sendTimeStampMessage:
    action: send
    channel: 
      $ref: '#/channels/echo'
    summary: Receive the timestamp message sent from server every second.
    messages:
      - $ref: '#/channels/echo/messages/timestamp'
  handleEchoMessage:
    action: receive
    channel: 
      $ref: '#/channels/echo'
    summary: Send a message to the echo server.
    messages:
      - $ref: '#/channels/echo/messages/echo'

components:
  messages:
    timestamp:
      summary: A message sent from server with current timestamp.
      payload: 
        $ref: '#/components/schemas/currentTime'
      examples:
        - name: someRandomDate
          payload: 11:13:24 GMT+0000 (Coordinated Universal Time)
    echo:
      summary: A message exchanged with the echo server.
      payload: {}
      examples:
        - name: string
          payload: "test"
        - name: boolean
          payload: true
        - name: number
          payload: 123
        - name: object
          payload: 
            test: test text
  
  schemas:
    currentTime:
      type: string
      description: A timestamp with GMT timezone.
      example: 11:13:24 GMT+0000 (Coordinated Universal Time)
```

It is pretty easy for me to understand the `send` part. When I connect to generated endpoint `localhost:8081/api/ws/Hoppscotch+WebSocket+Server/1.0.0/sendTimeStampMessage` with `websocat` I'm nicely receiving the example message:

```
websocat ws://localhost:8081/api/ws/Hoppscotch+WebSocket+Server/1.0.0/sendTimeStampMessage

11:13:24 GMT+0000 (Coordinated Universal Time)
11:13:24 GMT+0000 (Coordinated Universal Time)
```

I'm having hard time with `receive`: `localhost:8081/api/ws/Hoppscotch+WebSocket+Server/1.0.0/handleEchoMessage`

My understanding is that this endpoint is only for receiving messages. That I can drop to it anything I want. But when I do `websocat ws://localhost:8081/api/ws/Hoppscotch+WebSocket+Server/1.0.0/handleEchoMessage` I'm also seeing example messages sent from server.

This is what I also understood with https://microcks.io/documentation/guides/usage/async-protocols/avro-messaging/#without-schema-registry-1

I thought I can do below:

1. Run test
    ```
    curl -X POST http://localhost:8080/api/tests \
      -H "Content-Type: application/json" \
      -d '{
        "serviceId": "Hoppscotch WebSocket Server:1.0.0",
        "testEndpoint": "ws://localhost:8081/api/ws/Hoppscotch+WebSocket+Server/1.0.0/handleEchoMessage",
        "runnerType": "ASYNC_API_SCHEMA",
        "timeout": 30000,
        "filteredOperations": ["RECEIVE handleEchoMessage"]
      }'
    ```
1. Then start sending message to endpoint: `while true; do echo "hello" | websocat "ws://localhost:8081/api/ws/Hoppscotch+WebSocket+Server/1.0.0/handleEchoMessage"; sleep 1; done`
1. The test should receive not only mock examples, but also my `hello` messages - but it is not

So if my reasoning is wrong - then how things work. What is the purpose of `RECEIVE` mock? test runs only validate examples - nothing else

Not sure if I explain myself well.

**Comment by lbroudoux** [comment]
Hey @derberg,

This is actually one complex question that lies in (my?) concerns about deciding what the AsyncAPI document point of view is.  
My personal preference on this is to consider reading the AsyncAPI spec from the consumer's point of view. So typically, I best understand things when connecting to a `receive` endpoint allows me to retrieve mock messages that mimics an event producer... 😉

That said, Microcks supports both interpretations, and it's actually useful to have mock messages available on both types of endpoints - it's just useful from different perspectives.

With my interpretation in mind, I drew this diagram a few years ago and it eventually help others to understand why we had mocks on both types of endpoints:

<img width="1357" alt="Capture d’écran 2025-04-07 à 22 14 20" src="https://github.com/user-attachments/assets/ba7c7f62-7751-40a9-aa86-8325a606017a" />

Depending on the point of view you adopt:
* Having mock events can be useful for the _API consumer App_ **and** the _API provider App_. So Microcks publishes mocks on both kind of endpoints,
* Having contract testing capabilities can be useful for the _API consumer App_ **and** the _API provider App_. So Microcks tests can be executed on both kind of operations (ie. endpoints).

To sum up, it's just a matter of perspective and you'll probably just pick one or another type of endpoint when you focus on one side of the API. Hope it helps!

**Comment by derberg** [comment]
> This is actually one complex question that lies in (my?) concerns about deciding what the AsyncAPI document point of view is.

well you know the spec is pretty clear about it 😉 

Anyway, this is clear, so basically, mocks are produced for any type of operation. That's good to know.

What I still do not understand is how to `test if my real producer sends valid messages to mock consumer`.

In one terminal window I start sending messages:
```
while true; do echo "hello" | websocat "ws://localhost:8081/api/ws/Hoppscotch+WebSocket+Server/1.0.0/handleEchoMessage"; sleep 1; done
```

And in another start a test:
```
microcks-cli test 'Hoppscotch WebSocket Server:1.0.0' ws://localhost:8081/api/ws/Hoppscotch+WebSocket+Server/1.0.0/handleEchoMessage ASYNC_API_SCHEMA \
    --microcksURL=http://localhost:8080/api/ \
    --insecure \
    --waitFor=10sec \
    --keycloakClientId=microcks-serviceaccount \
    --keycloakClientSecret="ab54d329-e435-41ae-a900-ec6b3fe15c54" \
    --filteredOperations="[\"RECEIVE handleEchoMessage\"]"
```

And what I see in the test result is that it is getting the mock messages that `handleEchoMessage` sends by default (taken from `examples`), but I see no test result for incoming `hello` coming from the websocat client.

I'm obviously doing something wrong

**Reply by lbroudoux** [reply]
Ok. It's because the WS endpoints provided by Microcks (the ones at `/api/ws/<API Name>/<API Version>/`) are only used to send mock messages and not to receive messages.

However, if you have this echo server (let's say `node server.js`) that provides a WS endpoint (let's say `localhost:3000/ws/echo`) that can receive WS messages and broadcast them on the same endpoint, then you would be able to:

```sh
while true; do echo "hello" | websocat "ws://localhost:ws/echo"; sleep 1; done
```

one one side and then:

```sh
microcks-cli test 'Hoppscotch WebSocket Server:1.0.0' ws://localhost:3000/ws/echo ASYNC_API_SCHEMA \
    --microcksURL=http://localhost:8080/api/ \
    --insecure \
    --waitFor=10sec \
    --keycloakClientId=microcks-serviceaccount \
    --keycloakClientSecret="ab54d329-e435-41ae-a900-ec6b3fe15c54" \
    --filteredOperations="[\"RECEIVE handleEchoMessage\"]"
```

on another. In this situation, the Microcks test will connect to the application WS endpoint and ensure that messages available for consumption here (typically the one you send with `websocat`) are conformant to the message for the defined operaiton.

**Reply by derberg** [reply]
hmmm, let's assume I built my local server, it echo back whatever it gets. For that purpose I'm using real public echo `ws://ws.vi-server.org/mirror`

I start dending messages there `while true; do echo "hello" | websocat "ws://ws.vi-server.org/mirror"; sleep 1; done`

then I start test
```
microcks-cli test 'Hoppscotch WebSocket Server:1.0.0' ws://ws.vi-server.org/mirror ASYNC_API_SCHEMA \
    --microcksURL=http://localhost:8080/api/ \
    --insecure \
    --waitFor=15sec \
    --keycloakClientId=microcks-serviceaccount \
    --keycloakClientSecret="ab54d329-e435-41ae-a900-ec6b3fe15c54" \
    --filteredOperations="[\"RECEIVE handleEchoMessage\"]"
```

and the test never completes

<img width="1344" alt="Screenshot 2025-04-08 at 13 31 52" src="https://github.com/user-attachments/assets/7b0a9853-e173-4405-b70a-4d710348c72b" />

logs
```
MicrocksClient got status for test "67f508081c1336438e1284ca" - success: false, inProgress: true 
MicrocksTester waiting for 2 seconds before checking again or exiting.
MicrocksClient got status for test "67f508081c1336438e1284ca" - success: false, inProgress: true 
MicrocksTester waiting for 2 seconds before checking again or exiting.
MicrocksClient got status for test "67f508081c1336438e1284ca" - success: false, inProgress: true 
MicrocksTester waiting for 2 seconds before checking again or exiting.
MicrocksClient got status for test "67f508081c1336438e1284ca" - success: false, inProgress: true 
MicrocksTester waiting for 2 seconds before checking again or exiting.
MicrocksClient got status for test "67f508081c1336438e1284ca" - success: false, inProgress: true 
MicrocksTester waiting for 2 seconds before checking again or exiting.
MicrocksClient got status for test "67f508081c1336438e1284ca" - success: false, inProgress: true 
MicrocksTester waiting for 2 seconds before checking again or exiting.
MicrocksClient got status for test "67f508081c1336438e1284ca" - success: false, inProgress: true 
MicrocksTester waiting for 2 seconds before checking again or exiting.
MicrocksClient got status for test "67f508081c1336438e1284ca" - success: false, inProgress: true 
MicrocksTester waiting for 2 seconds before checking again or exiting.
MicrocksClient got status for test "67f508081c1336438e1284ca" - success: false, inProgress: true 
MicrocksTester waiting for 2 seconds before checking again or exiting.
MicrocksClient got status for test "67f508081c1336438e1284ca" - success: false, inProgress: true 
MicrocksTester waiting for 2 seconds before checking again or exiting.
MicrocksClient got status for test "67f508081c1336438e1284ca" - success: false, inProgress: true 
MicrocksTester waiting for 2 seconds before checking again or exiting.
MicrocksClient got status for test "67f508081c1336438e1284ca" - success: false, inProgress: true 
MicrocksTester waiting for 2 seconds before checking again or exiting.
MicrocksClient got status for test "67f508081c1336438e1284ca" - success: false, inProgress: true 
MicrocksTester waiting for 2 seconds before checking again or exiting.
Full TestResult details are available here: http://localhost:8080/#/tests/67f508081c1336438e1284ca 
```

even if this would work - what am I really testing?

Microcks sends mock events to `ws://ws.vi-server.org/mirror` and the once it received as echo are checked against schema?

Then even `while true; do echo "hello" | websocat "ws://ws.vi-server.org/mirror"; sleep 1; done` is not needed, or?

**Comment by lbroudoux** [comment]
> even if this would work - what am I really testing?
> 
> Microcks sends mock events to ws://ws.vi-server.org/mirror and the once it received as echo are checked against schema?

No. During a test, Microcks connects to `ws://ws.vi-server.org/mirror` and consumes messages. So you're testing that messages sent by your `echo | websocat` application are conformant to the schema of the `RECEIVE handleEchoMessage` operation.

Let me check on my side to have a running sample.

**Reply by derberg** [reply]
ok, for now I do not understand how Microcks could receive echo from `ws://ws.vi-server.org/mirror` if the message was sent from `websocat` client. Echo sends back to message author, not to all connected clients.

for me `websocat` and `Microcks` are independent clients, that connect to `ws://ws.vi-server.org/mirror` server.

hmmm 🤔

**Reply by lbroudoux** [reply]
Oh ok. I wasn't aware of websocat and echo/mirror behavior. Let me find my simple example to be sure we share common grounds and then we'll see if some things somehow may be enhanced. I'll start my day with this on tomorrow morning.

**Reply by derberg** [reply]
Ok, so now I have my local websocket server

```
const port = 8082;

const wsServer = new WebSocket.Server({ port }, () => {
    console.log(`Test WS server running on port ${port}`);
  });

wsServer.on('connection', (socket) => {
      console.log('Client connected to test server');
      socket.send('Welcome to the WebSocket server!');
    });

function broadcast(message) {
      wsServer.clients.forEach(client => {
        if (client.readyState === WebSocket.OPEN) {
          client.send(message);
        }
      });
    }
    
// For demonstration, broadcast a message every 10 seconds.
setInterval(() => {
      broadcast('Periodic broadcast message');
    }, 100);
```

As you can see it broadcast the same message to all connected clients

```
websocat ws://localhost:8082
Welcome to the WebSocket server!
Periodic broadcast message
Periodic broadcast message
Periodic broadcast message
Periodic broadcast message
```

`websocat` client works like a charm. Connects, gets welcome, and starts receiving

but when I start test on Microcks

```
microcks-cli test 'Hoppscotch WebSocket Server:1.0.0' ws://localhost:8082 ASYNC_API_SCHEMA \
    --microcksURL=http://localhost:8080/api/ \
    --insecure \
    --waitFor=15sec \
    --keycloakClientId=microcks-serviceaccount \
    --keycloakClientSecret="ab54d329-e435-41ae-a900-ec6b3fe15c54" \
    --filteredOperations="[\"RECEIVE handleEchoMessage\"]"
```

test fail, and in logs I do not even see that Microcks tried to connect to `ws://localhost:8082`


not much info in UI
<img width="1326" alt="Screenshot 2025-04-08 at 22 23 37" src="https://github.com/user-attachments/assets/70524f86-193e-47aa-b867-bc4b1cfd9495" />

**Reply by lbroudoux** [reply]
Ok. I suppose you're running Microcks in a container right? In that case, the address of your WS endpoint is not `ws://localhost:8082` but `ws://host.docker.internal:8082`. You need the alias that allows the Microcks container to reach the host network (from the container POV, `localhost` means itself).

**Reply by lbroudoux** [reply]
I found the test application I was using for checking all of this and it's located here: https://github.com/microcks/api-tooling/tree/main/async-clients/wsjs-client. If you're available during the morning, we can have a quick video call to review this.

**Reply by derberg** [reply]
thanks so much for the great direction.....yeah, I forgot the basics about networking in containers.

so 2 things have to be solved on my side.

tl;dr
- now my tests run also in container in the same network that microcks - much better and leaner setup imho
- I had to adjust one thing in my test, the only thing that was different compared with `https://github.com/microcks/api-tooling/blob/main/async-clients/wsjs-client/server.js`. It was a change from `new WebSocket.Server({ port }` to `new WebSocket.Server({ port, path: '/ws' }`. Yup, `path`. Without it, fails big time, and the moment I add a custom path, all good. Probably some picky handling on jakarta side 🤷🏼 anyway, not a big deal for me.

Sharing for others if they are every ending up here and need help.

My podman compose setup for microcks with test invocation using `tests` profile:

```yaml
volumes:
  microcks-data:
  
services:
  mongo:
    image: docker.io/mongo:4.4.29
    container_name: microcks-db
    volumes:
      - microcks-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 1s
      retries: 3

  kafka:
    image: docker.io/redpandadata/redpanda:v24.3.1
    container_name: microcks-kafka
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka:19092,EXTERNAL://localhost:9092
    ports:
      - 9092:9092
      - 19092:19092
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c 'echo > /dev/tcp/localhost/19092'"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  app:
    depends_on:
      - mongo
    image: quay.io/microcks/microcks:1.11.2
    container_name: microcks
    volumes:
      - ./config:/deployments/config:Z
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_DATA_MONGODB_DATABASE: microcks
      POSTMAN_RUNNER_URL: http://postman:3000
      TEST_CALLBACK_URL: http://microcks:8080
      SERVICES_UPDATE_INTERVAL: "0 0 0/2 * * *"
      KEYCLOAK_ENABLED: "false"
      #MAX_UPLOAD_FILE_SIZE: 3MB
      ASYNC_MINION_URL: http://microcks-async-minion:8081
      KAFKA_BOOTSTRAP_SERVER: kafka:19092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      start_period: 35s
      interval: 10s
      timeout: 3s
      retries: 3

  async-minion:
    depends_on:
      - app
    image: quay.io/microcks/microcks-async-minion:1.11.2
    container_name: microcks-async-minion
    restart: on-failure
    volumes:
      - ./config:/deployments/config:Z
    ports:
      - 8081:8081
    environment:
      QUARKUS_PROFILE: docker-compose
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/q/health/ready"]
      start_period: 10s
      interval: 10s
      timeout: 2s
      retries: 3
  
  importer:
    profiles:
      - tests
    image: quay.io/microcks/microcks-cli:latest
    container_name: microcks-cli-importer
    working_dir: /usr/src/app
    volumes:
      - ../:/usr/src/app
    depends_on:
      app:
        condition: service_healthy
    command: >
      sh -c "microcks-cli import __fixtures__/asyncapi-hoppscotch-server.yml
      --microcksURL=http://microcks:8080/api/
      --keycloakClientId=microcks-serviceaccount
      --keycloakClientSecret=ab54d329-e435-41ae-a900-ec6b3fe15c54"

  tester:
    profiles:
      - tests
    image: node:18
    container_name: websocket-acceptance-tester
    ports:
      - 8082:8082
    working_dir: /usr/src/app
    volumes:
      - ../../../../../../:/usr/src/app
    depends_on:
      app:
        condition: service_healthy
    command: ["sh", "-c", "npm install && cd packages/templates/clients/websocket/test/javascript && npm test"]
```

my js acceptance test:

```js
//acceptance.test.js

const WSClient = require('../../javascript/test/temp/snapshotTestResult/client-hoppscotch');
const { waitForMessage, delay, waitForTestSuccess } = require('./utils');
const fetch = require('node-fetch');
const WebSocket = require('ws');
const microcksTestEndpoint = 'http://microcks:8080/api/tests';

describe('client - receiver tests', () => {
  jest.setTimeout(10000);
  /*
  * TEST: we test if the generated client can be instantiated with custom URL
  */
  const wsClient = new WSClient(
    'ws://microcks-async-minion:8081/api/ws/Hoppscotch+WebSocket+Server/1.0.0/sendTimeStampMessage'
  );

  it('javascript client should receive a message', async () => {
    const received_messages = [];
    const expectedMessage = '11:13:24 GMT+0000 (Coordinated Universal Time)';

    /*
    * TEST: we test if generated message handler can be registered and later records messages
    */
    // registering message handler that adds incomming messages to an array
    // later messages from array are evaluated to make sure the message sent from server is received by the client
    wsClient.registerMessageHandler((message) => {
      received_messages.push(message);
    });

    /*
    * TEST: we test if we can connect to server using genrated client
    */
    await wsClient.connect();

    // wait for the incomming message to be logged
    await waitForMessage(received_messages, expectedMessage);

    const isReceived = received_messages.some((message) =>
      message.includes(expectedMessage)
    );

    // checking if microcks mock send proper message and they were recorded by registered handler for incomming messages
    expect(isReceived).toEqual(true);
  });

  afterAll(async () => {
    wsClient.close();

    //jest doesn't like that on client closure some logs are printed
    // so we need to wait second or 2 until all logs are printed
    await delay();
  });
});

describe('client - sender tests', () => {
  jest.setTimeout(100000);
  const port = 8082;
  const payload = JSON.stringify({
    serviceId: 'Hoppscotch WebSocket Server:1.0.0',
    testEndpoint: 'ws://websocket-acceptance-tester:8082/ws',
    runnerType: 'ASYNC_API_SCHEMA',
    timeout: 30000,
    filteredOperations: ['RECEIVE handleEchoMessage'],
  });

  //this is a custom server that needs to be used to expose endpoint to which microcks will connect and await for messages comming from generated function
  const wsServer = new WebSocket.Server({ port, path: '/ws' }, () => {
    console.log(`Test WS server running on port ${port}`);
  });

  it('javascript client should send a valid message', async () => {
    //await delay(100000);
    const expectedMessage = 'Sending acceptance test message';

    wsServer.on('connection', (socket) => {
      /*
      * TEST: sending message with generated function to microcks test client that connected to our custom server
      */
      WSClient.sendEchoMessage(expectedMessage, socket);
    });

    // Start test in Microcks
    const response = await fetch(microcksTestEndpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: payload,
    });

    //checking test result
    const responseBody = await response.json();
    const status = await waitForTestSuccess(`${microcksTestEndpoint}/${responseBody.id}`);

    expect(status).toEqual(true);
  });

  afterAll(async () => {
    wsServer.close();
    //jest doesn't like that on client closure some logs are printed
    // so we need to wait second or 2 until all logs are printed
    await delay();
  });
});

//utils.js
const fetch = require('node-fetch');

/**
 * Polls the Microcks API every 2 seconds until a test with the given ID reports success.
 *
 * @param {string} url - link to endpoint providing info on particular test
 * @returns {Promise<boolean>} Resolves with `true` when the test is marked as successful.
 */
async function waitForTestSuccess(url) {
  while (true) {
    try {
      const response = await fetch(url, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' }
      });

      if (!response.ok) {
        console.error(`Request failed with status: ${response.status}`);
        break;
      }

      const data = await response.json();

      if (data.success) {
        return true;
      }
    } catch (err) {
      break;
    }

    await new Promise(resolve => setTimeout(resolve, 2000)); // Wait 2 seconds
  }

  return false;
}

/**
 * Wait for a specific message to appear in the spy's log calls.
 * @param {array} a - array with messages
 * @param {string} expectedMessage - The message to look for in logs.
 * @param {number} timeout - Maximum time (in ms) to wait. Default is 3000ms.
 * @param {number} interval - How long to wait (in ms) until next check. Default is 10ms.
 * @returns {Promise<void>} Resolves if the message is found, otherwise rejects.
 */
async function waitForMessage(a, expectedMessage, timeout = 3000, interval = 10) {
  const start = Date.now();
  while (Date.now() - start < timeout) {
    if (a.some(message => message.includes(expectedMessage))) {
      return;
    }
    await delay(interval);
  }
  throw new Error(`Expected message "${expectedMessage}" not found within timeout`);
}
  
/**
   * Delay execution by a specified time.
   * @param {number} time - Delay duration in milliseconds. Default is 1000ms.
   * @returns {Promise<void>} Resolves after the specified delay.
   */
async function delay(time = 1000) {
  return new Promise(resolve => setTimeout(resolve, time));
}
  
module.exports = {
  waitForMessage,
  delay,
  waitForTestSuccess
};
```

I should probably write down some article to share all I learned to somehow pay back for your help
