### DISCUSSION TITLE
Set dynamic parameters

### DISCUSSION THREAD

**Discussion by mflasquin** [microcks/microcks#634] [Q&A] [answered]
Hi,
Is it possible to define dynamic parameters ? Like this :

```
      parameters:
        - name: id
          in: path
          description: Contact id
          required: true
          schema:
            type: integer
            format: int64
          examples:
              get-1761114:
                  value: "{{ randomInt(5,10) }}"
```

Thanks
