### DISCUSSION TITLE
Can't load external exemples (relative paths)

### DISCUSSION THREAD

**Discussion by oliviernguyenquoc** [microcks/microcks#916] [Q&A] [answered]
I have examples in my 3.1 OpenAPI specifications like that:

```yaml
components:
  examples:
    firstExample:
      summary: A sample example
      externalValue: "./fixtures/output/examples.json#/0"
```

When I import my yaml file, I got an error:

```
Error loading external example: 
http://localhost:8080/api/resources/fixtures/output/examples.json#/0
```

Please note that I'm using "Direct upload artifact" feature and when I try to use "Is a Secondary Artifact ?   Just merge examples into existing API | Service definition. " select box, I have a success message but  nothing appear in "APIs & Services" section

Any idea ? Any process to load these external files ?

**Comment by lbroudoux** [comment]
Hello @oliviernguyenquoc,

As of today, we do not follow refs provided by `externalValue` but just the one provided by `$ref`. So something like:

```yaml
components:
  examples:
    firstExample:
      $ref: './fixtures/output/examples.json'
```

may work (not sure we're handling the subsequent path correctly though). 

This could be a nice enhancement to bring to the OpenAPI importer.
