### ISSUE TITLE
pb with customize helm values username from keycloack postgres user

### ISSUE THREAD

**Issue by sburky** [microcks/microcks#1026]
### Describe the bug

when keycloack.username is customized , the container can't start with message 'database root does not exist'... 

### How to Reproduce?

```yaml
keycloak:
  install: true
  realm: microcks
  # Now that we switched to newer version of Keycloak-X, default url does not contain '/auth' path
  # If you use an older external Keycloak instance, url must include the '/auth' path
  #url: keycloak-microcks.192.168.99.100.nip.io
  privateUrl: http://microcks-keycloak.microcks.svc.cluster.local:8080
  #ingressSecretRef: my-secret-for-keycloak-ingress
  #ingressAnnotations:
  #cert-manager.io/issuer: my-cert-issuer
  #kubernetes.io/tls-acme: "true"
  #ingressClassName: nginx
  #pvcAnnotations:
  #helm.sh/resource-policy: keep
  generateCert: true
  image: quay.io/keycloak/keycloak:22.0.3
  adminUsername: admin
  # Unless you uncomment following line, admin password will be randomly generated.
  # Beware that in case of update, new value will be generated and
  adminPassword: admin123

  # Uncomment to change Keycloak Service to a NodePort
  #serviceType: NodePort

  resources:
    requests:
      cpu: 400m
      memory: 400Mi
    limits:
    #cpu: 500m
    #memory: 512Mi

  persistent: true
  volumeSize: 1Gi
  # Unless you uncomment following line and set class, persistent volume claim is created
  # with no storage class and relies on cluster default one.
  #storageClassName: my-awesome-class
  postgresImage: centos/postgresql-95-centos7:latest
  #username: postgres
  # Unless you uncomment following line, admin password will be randomly generated.
  # Beware that in case of update, new value will be generated and overwrite existing one.
  password: admin123
```

### Microcks version or git rev

1.8.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

helm chart

**Comment by lbroudoux** [comment]
Hey! Thanks a lot for opening this one. TBH I think I've never tested this one. Will have a look at it shortly.

**Comment by lbroudoux** [comment]
Hello,
I've run a quick test on my local minikube installation and things are working correctly when you're setting both `username` and `password. This is the command line I've used for this:

```sh
$ helm install microcks ./microcks --namespace microcks3 --set microcks.url=microcks.m3.minikube.local --set keycloak.url=keycloak.m3.minikube.local --set keycloak.privateUrl=http://microcks-keycloak.microcks3.svc.cluster.local:8080 --set keycloak.username=toto --set keycloak.password=toto123
```

I think that you get this error because the `username` is commented in your `values.yaml` file above:

```yaml
  [...]
  postgresImage: centos/postgresql-95-centos7:latest
  #username: postgres
  # Unless you uncomment following line, admin password will be randomly generated.
  # Beware that in case of update, new value will be generated and overwrite existing one.
  password: admin123
```

Closing this issue for now, feel free to re-open it if that was not the correct explanation.
