### ISSUE TITLE
Non mandatory query param marked as allowEmptyValue:true cause exception if set to empty in the URL

### ISSUE THREAD

**Issue by ArnaudCharpentier** [microcks/microcks#1189]
### Describe the bug

Given a openapi file with declared query params like :

```yaml
     parameters:
        - name: param1
          in: query
          required: false
          allowEmptyValue: true
          schema:
            type: string
        - name: param2
          in: query
          required: false
          allowEmptyValue: true
          schema:
            type: string
```

Query params are mentionned as non required and empty value are allowed.
If I call my endpoint with an empty value, it cause an 500 error. It shouldn't.

### Expected behavior

Expect do receive a 200 OK

### Actual behavior

Receive a 500 Internal server Error 
Stack trace is 
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
2024-05-29 21:08:31     at io.github.microcks.util.DispatchCriteriaHelper.extractFromURIParams(DispatchCriteriaHelper.java:426)
2024-05-29 21:08:31     at io.github.microcks.web.RestController.computeDispatchCriteria(RestController.java:333)
2024-05-29 21:08:31     at io.github.microcks.web.RestController.execute(RestController.java:191)
```

### How to Reproduce?

Import given modified pastry openapi file [sample.yml.zip](https://github.com/microcks/microcks/files/15489916/sample.yml.zip)
Try to call http://localhost:8080/rest/API+Pastry+-+2.0/2.0.0/pastry?param1=test&param2=
It will fail
http://localhost:8080/rest/API+Pastry+-+2.0/2.0.0/pastry?param1=test is OK

### Microcks version or git rev

1.9.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

helm chart
