### ISSUE TITLE
Helm chart image registry variable(s)

### ISSUE THREAD

**Issue by rquinio1A** [microcks/microcks#1211]
### Reason/Context

We have to use a corporate proxy to cache container images.
It is possible to do it with the existing chart, but it requires to override the full image coordinates:

```yaml
microcks:
  microcks:
    image: my-registry/my-quay-io-remote/microcks/microcks:1.9.1
  mongodb:
    image: my-registry/my-docker-io-remote/centos/mongodb-36-centos7:latest
  postman:
    image: my-registry/my-quay-io-remote/microcks/microcks-postman-runtime:0.4.0
  features:
    async:
      image: my-registry/my-quay-io-remote/microcks/microcks-async-minion:1.9.1
```

This makes updating the chart a bit more painful, as you need to align all the tags as well.

### Description

There should be Helm variable(s) to override the registry+namespace part of the image (my-registry/my-quay-io-remote and my-registry/my-docker-io-remote)

The most flexible charts even split things a bit further with ability to also override tag and even digest:
* https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml#L25-L31
* https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml#L165-L172
* https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/values.yaml#L15-L19

**Comment by lbroudoux** [comment]
Hey @rquinio1A,
This sounds like a very reasonable enhancement 😉 
As there is some work in progress regarding Help Chart (see #1197 and #1200), we have to look how we can integrate this in the same batch.

**Comment by lbroudoux** [comment]
Hey,
I just looked at it and the other Helm charts you provide as references. If we apply the same logic, it would mean 
that you would have to maintain such properties in your `values.yaml` (if you rely on default images of course) :

```yaml
microcks:
  microcks:
    image: 
      registry: my-registry/my-quay-io-remote
      tag: 1.9.1
  mongodb:
    image: 
      registry: my-registry/my-docker-io-remote
      tag: latest
  postman:
    image: 
      registry: my-registry/my-quay-io-remote
      tag: 0.4.0
  features:
    async:
      image: 
        registry: my-registry/my-quay-io-remote
        tag: 1.9.1
```

Did I get it correctly? Is it really less painful than having the complete image coordinates expressed as a single value?

**Comment by lbroudoux** [comment]
Now done!

You can now fully specify the different images using this kind of declaration:

```yaml
microcks:
  image:
    registry: quay.io
    repository: microcks/microcks
    tag: nightly
    digest:
```
