### ISSUE TITLE
Define Microcks' own API examples specification artifact

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1241]
### Reason/Context

Currently, when one wants to define mocks for a GraphQL API or a gRPC service, people need to use Postman Collection as a secondary artifact to specify their mock dataset. Once Postman Collection is quite popular, it happens that some development teams or functional experts are not familiar with it and prefer using a raw text editor.

We had several requests from team asking for a lightweight specification format of mock datasets that would not rely on Postman Collection to keep the Microcks adoption curve very smooth within the development teams.

### Description

While Microcks' moto is to not reinvent the wheel and reuse standard artifacts (see [artifacts reference](https://microcks.io/documentation/references/artifacts/)), we think it may be the time to introduce our own specification format that will be totally driven by the goal of importing mock datasets into Microcks. This format would be used as a secondary artifact format and would be the companion of our existing `APIMetada` format (see [APIMetadata](https://microcks.io/documentation/references/metadada/)) but dedicate to API Examples.

### Implementation ideas

The idea would be to mimic the `APIMetadata` specification format and having something super-simple to specify request/response pairs or event additional asynchronous event messages (thus it would be used as a secondary artifact to an AsyncAPI primary specification).

Those first design ideas come to my mind - for an REST API case:

```yaml
apiVersion: mocks.microcks.io/v1alpha1
kind: APIExamples
metadata:
  name: API Pastry - 2.0
  version: 2.0.0
operations:
  'GET /pastry/{name}':
    Eclair Chocolat:
      request:
        parameters:
          name: Eclair Chocolat
      response:
        mediaType: application/json
        body:
          name: Eclair Chocolat
          description: Delicieux Eclair Chocolat pas calorique du tout
          size: M
          price: 2.5
          status: unknown
    Eclair Chocolat Xml:
      request:
        parameters:
          name: Eclair Chocolat Xml
      response:
        mediaType: text/xml
        body: |-
          <pastry>
            <name>Eclair Cafe</name>
            <description>Delicieux Eclair au Chocolat pas calorique du tout</description>
            <size>M</size>
            <price>2.5</price>
            <status>unknown</status>
          </pastry>
```

For a gRPC service:

```yaml
apiVersion: mocks.microcks.io/v1alpha1
kind: APIExamples
metadata:
  name: io.github.microcks.grpc.hello.v1.HelloService
  version: v1
operations:
  'greeting':
    Laurent:
      request:
        body:
          firstname: Laurent
          lastname: Broudoux
      response:
        body:
          greeting: Hello Laurent Broudoux !
    John:
      request:
        body: |-
          {"firstname": "John", "lastname": "Doe"}
      response:
        body:
          greeting: Hello John Doe !
```

For an AsyncAPI service:
```yaml
apiVersion: mocks.microcks.io/v1alpha1
kind: APIExamples
metadata:
  name: User signed-up API
  version: 0.1.0
operations:
  'SUBSCRIBE /user/signedup':
    jane:
      headers:
        my-app-header: 123
        sentAt: "2024-07-14T18:01:28Z"
      payload:
        fullName: Jane Doe
        email: jane@microcks.io
        age: 35
```
