### ISSUE TITLE
microcks 1.10.0 chart conflicts with the mongodb bitnami chart.

### ISSUE THREAD

**Issue by rquinio1A** [microcks/microcks#1263]
### Describe the bug

When both microcks and bitnami mongodb chart are included in the same umbrella chart, there's an Helm error:

```
Error: template: umbrella/charts/mongodb/templates/standalone/dep-sts.yaml:93:12: executing "umbrella/charts/mongodb/templates/standalone/dep-sts.yaml" at <include "mongodb.initContainer.prepareLogDir" .>: error calling include: template: umbrella/charts/mongodb/templates/_helpers.tpl:276:12: executing "mongodb.initContainer.prepareLogDir" at <include "mongodb.image" .>: error calling include: template: umbrella/charts/microcks/templates/_helpers.tpl:103:52: executing "mongodb.image" at <.Values.mongodb.image>: nil pointer evaluating interface {}.image
```

Both charts happen to define the "mongodb.image" named template.

### How to Reproduce?

Create an umbrella with:

```yaml
dependencies:
- name: mongodb
  version: 15.6.16
  repository: alias:bitnami
- name: microcks
  version: 1.10.0
  repository: alias:microcks
```
