### ISSUE TITLE
[APIExamples] Bug when importing with POST request when there is path param and query param

### ISSUE THREAD

**Issue by tpitteman** [microcks/microcks#1281]
### Describe the bug

When I decided to create in an first time a swagger without examples with a POST URL who contains **path param** and **query param** ( swagger_without_examples.json ) and in a second time i try to merge example into it ( details of the merge_examples1.1.0.yml file indicated in Additionnal info part bcos .yml aren't supported in attached files ) I saw that the  mock URL wasn't constructed properly, as a result I have : 
https://myhostname/rest/merge-example/1.1.0/workspaces/members/by-workspace/1y2u2i3o4p5p7h-F1h3/by-usernames?username=test@test.com&workspaceId=1y2u2i3o4p5p7h-F1h3

### Expected behavior

The expected behaviour would be regarding the mock URL :
https://myhostname/rest/merge-example/1.1.0/workspaces/members/by-workspace/1y2u2i3o4p5p7h-F1h3/by-usernames?username=test@test.com
And the cURL command should work accordingly.

### Actual behavior

Once the two files are updated ( swagger and examples ) the mock URL is showing the path parameter twice : https://myhostname/rest/merge-example/1.1.0/workspaces/members/by-workspace/1y2u2i3o4p5p7h-F1h3/by-usernames?username=test@test.com&workspaceId=1y2u2i3o4p5p7h-F1h3
And when I use the cURL command, I have this result : 
"The response /workspaceId=1y2u2i3o4p5p7h-F1h3?username=test@test.com?workspaceId=1y2u2i3o4p5p7h-F1h3 does not exist!"

### How to Reproduce?

You can update first the swagger_without_examples.json file ( in importers section ) and then create the 2nd file with the informations indicated in additionnal part (merge_example1.1.0.yml - in importers section with the checkbox tilled )
[swagger_without_examples.json](https://github.com/user-attachments/files/16728669/swagger_without_examples.json)
( the .yml format isn't supported as attached file here, I've filled the details in additionnal information part )

### Microcks version or git rev

1.10

### Additional information

Here under the details of merge_examples1.1.0.yml : 

```
apiVersion: mocks.microcks.io/v1alpha1
kind: APIExamples
metadata:
  name: merge-example
  version: 1.1.0

operations:
  'POST /workspaces/members/by-workspace/{workspaceId}/by-usernames':
    already member:
      request:
        parameters:
          workspaceId: 1y2u2i3o4p5p7h-F1h3
          username: test@test.com
      response:
        status: 409
        mediaType: application/json
        body: |-
          {
            "message": "test@test.com is already member of this workspace",
            "type": "IllegalStateException"
          }
```
