### ISSUE TITLE
UI - error in widget renderer for APIExamples merge with body mock template

### ISSUE THREAD

**Issue by SylvainDumas** [microcks/microcks#1288]
### Describe the bug

Version 1.10.0 & nightly

When you import an OpenAPI service, and merge metdata and example, a service is created in Microcks UI and interface gives you a MockURL for that expected example and the body of the response

With files provided, service is created, routing is working well as expected, but you do not see tab request for the corresponding example, or tabs appear but one of them does not have content.

May be another side effect is that merging 2 examples with 1 common examples duplicates it

Regards

### Expected behavior

Merging examples must give tab with MockURL filled, and response body displayed
Merging examples with same name (as identifier) must replace it, not create another copy

### Actual behavior

For import of swagger and merge of **examples1.yml** and **metadata.yml** you get
<img width="1455" alt="image" src="https://github.com/user-attachments/assets/a50acfc5-4fd3-4d27-9067-c2a0729c46fc">

For import of swagger and merge of **examples2.yml** and **metadata.yml** you get
By selecting tab **list**
<img width="1455" alt="image" src="https://github.com/user-attachments/assets/df81f71f-01c1-4269-a7ef-915711e2d035">

By selecting tab **titi**
<img width="1455" alt="image" src="https://github.com/user-attachments/assets/e11e18f4-07d6-4189-a1b6-8a0d80658101">

For import of swagger and merge of **metadata.yml**, then **examples1.yml**, then **examples2.yml** and  you get
<img width="1455" alt="image" src="https://github.com/user-attachments/assets/c37424e5-03c1-445a-980a-465027c96216">

Please note the 4 samples, but expecting 3 because of replacing previous example with same name does not work
And no tabs

### How to Reproduce?

Import swagger
[swagger.json](https://github.com/user-attachments/files/16762413/swagger.json)

Merge in any order
**metadata.yml** file
```yaml
apiVersion: mocks.microcks.io/v1alpha1
kind: APIMetadata
metadata:
  name: statefull
  version: 1.0.0

operations:
  'GET /workspaces/{workspaceId}':
    delay: 100
    dispatcher: SCRIPT
    dispatcherRules: |-
      requestContext.items = "foo"
      return "list"
```

**examples1.yml** file
```yaml
apiVersion: mocks.microcks.io/v1alpha1
kind: APIExamples
metadata:
  name: statefull
  version: 1.0.0

operations:
  'GET /workspaces/{workspaceId}':
    list:
      request:
        parameters:
          workspaceId: list
      response:
        status: 200
        mediaType: application/json
        body: '{{ items }}'
```

**examples2.yml** file
```yaml
apiVersion: mocks.microcks.io/v1alpha1
kind: APIExamples
metadata:
  name: statefull
  version: 1.0.0

operations:
  'GET /workspaces/{workspaceId}':
    titi:
      request:
        parameters:
          workspaceId: titi
      response:
        status: 404
        mediaType: application/json
        body: '{"error" : "titi"}'
    list:
      request:
        parameters:
          workspaceId: list
      response:
        status: 200
        mediaType: application/json
        body: '{{ items }}'
    unknown:
      request:
        parameters:
          workspaceId: unknown
      response:
        status: 404
        mediaType: application/json
        body: '{"error" : "baz"}'
```

Open a navigator on url http://localhost:8080/rest/statefull/1.0.0/workspaces/tom

### Microcks version or git rev

1.10.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose, helm, ...
