### ISSUE TITLE
Authentication 401 Errors using Docker Compose for Mac

### ISSUE THREAD

**Issue by yahehe** [microcks/microcks#131]
I'm experiencing some confusing behavior using Microcks with Docker Compose for Mac, and it seems to all boil down to the authentication.

I'm able to spin up the containers locally and log in through the site. I should note that I *am* able to access the keycloak server at `http://localhost:8180`, so it does not appear to have the same root cause as other issues filed.

When I attempt to view the list of APIs & Services, by default I get a 401 Unauthorized error, with the response header `WWW-Authenticate: Bearer realm="microcks", error="invalid_token", error_description="Didn't find publicKey for specified kid"`. When I filter the list with any character the API succeeds and returns the expected data.
![image](https://user-images.githubusercontent.com/6528050/55344923-b623fb00-547c-11e9-8a13-1ce1e63232e6.png)
JWT used:
```
eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ5Mi11UF9kbjBxa19GVncxVHpVNFhXck1BUEJ6Qkh6ZlhHV29hMDRRNkFFIn0.eyJqdGkiOiJmNmFiMWRlZC02YWYzLTRhMGQtYjkyMi1jZGUwNzgzNmU1NmEiLCJleHAiOjE1NTQxMzcwOTAsIm5iZiI6MCwiaWF0IjoxNTU0MTM2NzkwLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgxODAvYXV0aC9yZWFsbXMvbWljcm9ja3MiLCJhdWQiOiJtaWNyb2Nrcy1hcHAtanMiLCJzdWIiOiJmYjRkZjQ0Yy1jYjE1LTRjNDktOTA1MS0yMTRmOGU4YzJlOWMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJtaWNyb2Nrcy1hcHAtanMiLCJub25jZSI6ImE3MWIxNmE4LTYxMzUtNDM4OS1hYjEyLTdmMmZhNWZhZGJmYyIsImF1dGhfdGltZSI6MTU1NDEzNTI1Mywic2Vzc2lvbl9zdGF0ZSI6IjcwNDZlNDU0LTQ4NDMtNDM1Mi1iNDlmLTdmY2QzYzllZDdhOCIsImFjciI6IjAiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJhZG1pbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJ2aWV3LXJlYWxtIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJyZWFsbS1hZG1pbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIl19fSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.IwlvEeXaq2u9qGVawrEM9eJ5rSRFR61HNycznUddIJhOt5W0Q2Xgx0wPzS1FVMw2RycF9E9jo1jsnydfMjW8hEIZqEIdmBVqkskE0ADP2-AhK4Duxvhi8FBTVGhgezTfbe04GDlAoPxOqfJigBOcIOgZIEsBAEQPi_L4ENlv6Fp7eDqOB1wGTQUTsSAJlLTAqUM4HxGb4h_wQt6M0CtedKUpDuBBkyaLcWfbIneZUdArM1FkecdgSRAV5LBocbQojGJxo1plcoLBHoao4U7T-iTnp34IdYplF3dE4BaE9o0NpeIhxMSTNExhkiLBJ7Vfno0okAJGTL8Ux89BD68s-g
```

This issue appears to affect import job creation as well:
![image](https://user-images.githubusercontent.com/6528050/55345070-0733ef00-547d-11e9-8374-e604726caf83.png)
JWT used:
```
eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ5Mi11UF9kbjBxa19GVncxVHpVNFhXck1BUEJ6Qkh6ZlhHV29hMDRRNkFFIn0.eyJqdGkiOiI4Nzc2MzA3Ny0zNGI0LTQzMTktYTYzNC05OTE3MGFmYmYzZDgiLCJleHAiOjE1NTQxMzc2MzAsIm5iZiI6MCwiaWF0IjoxNTU0MTM3MzMwLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgxODAvYXV0aC9yZWFsbXMvbWljcm9ja3MiLCJhdWQiOiJtaWNyb2Nrcy1hcHAtanMiLCJzdWIiOiJmYjRkZjQ0Yy1jYjE1LTRjNDktOTA1MS0yMTRmOGU4YzJlOWMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJtaWNyb2Nrcy1hcHAtanMiLCJub25jZSI6ImE3MWIxNmE4LTYxMzUtNDM4OS1hYjEyLTdmMmZhNWZhZGJmYyIsImF1dGhfdGltZSI6MTU1NDEzNTI1Mywic2Vzc2lvbl9zdGF0ZSI6IjcwNDZlNDU0LTQ4NDMtNDM1Mi1iNDlmLTdmY2QzYzllZDdhOCIsImFjciI6IjAiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJhZG1pbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJ2aWV3LXJlYWxtIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJyZWFsbS1hZG1pbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIl19fSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.CwQVksbDe2vL3QvKqklGrDQw4k2JkMuwD1bT8rwRRzCJwVha8LkW7jKqy93rgGEo3ind2kbiBNsIb4-EvxB325JHjK9ImTMEQL4fHy873v1M2Y3XcUF1_Xn7nBuCV6WiwG65unD3sUJnNHtl9UL5c5DFx6BC2EGOg2_qKhwThV7BhG4eAUq8WZp-Iiz_Pbz-Zyg54U0GbhlcbW8yEo8fgcUDnDsSECONp1FOFjP6zni-PuKo6Kev6NME16PSSgdz3MRPBC3UituqVHnAtkODx-HlvW2pEKp2gmH2JnqRQb63vAXDiB2eN3Jd0sgaBlV8BF4QM1I3r5GH8m21V8rBFg
```

OSX Version 10.14.3 (18D109)
Docker version 18.09.2, build 6247962
docker-compose version 1.23.2, build 1110ad01

Relates to #14

**Comment by lbroudoux** [comment]
Hi @yahehe,

Thanks for trying out Microcks! A quick question: have your edited the `microcks.yml` file before launching Docker compose? An extra step is necessary on Mac OS, you should comment out the default `KEYCLOAK_URL` env var and uncomment the one specific for Mac OS. Documentation is a little bit out-of-date... sorry.

So you should end up with something like that:
```
[...]
      #- KEYCLOAK_URL=http://localhost:8180/auth
      - KEYCLOAK_URL=http://docker.for.mac.localhost:8180/auth
      #- KEYCLOAK_URL=http://docker.for.win.localhost:8180/auth
[...]
```
just before launching everything.

I have just re-test right now and have an environment very similar to yours:

OSX Version 10.14 (18A391)
Docker version 18.09.1, build 4c52b90
docker-compose version 1.23.2, build 1110ad01

Let me know if it helps.

**Comment by yahehe** [comment]
@lbroudoux I attempted that last night and ran into an issue where loading the UI displays an error saying there was an authentication subsystem initialization failure. I waited longer today and eventually the UI loaded but I'm experiencing the same issue, I ran the following with the config updated as you suggested:
```
╭─cdowney@bos049 ~/personal/microcks/install/docker-compose/microck
s/install/docker-compose  ‹master› 
╰─$ docker-compose -f microcks.yml down
Stopping microcks                 ... done
Stopping microcks-keycloak        ... done
Stopping microcks-postman-runtime ... done
Stopping microcks-mongo           ... done
Removing microcks                 ... done
Removing microcks-keycloak        ... done
Removing microcks-postman-runtime ... done
Removing microcks-mongo           ... done
Removing network docker-compose_main
╭─cdowney@bos049 ~/personal/microcks/install/docker-compose/microcks/install/docker-compose  ‹master› 
╰─$ docker-compose -f microcks.yml up -d
Creating network "docker-compose_main" with the default driver
Creating microcks-keycloak        ... done
Creating microcks-postman-runtime ... done
Creating microcks-mongo           ... done
Creating microcks                 ... done
```
I then went to the API & Services tab and saw the following again:
![image](https://user-images.githubusercontent.com/6528050/55360089-699ee680-54a1-11e9-8965-93b43e602e80.png)

**Comment by yahehe** [comment]
UI token refresh appears to be working:
![image](https://user-images.githubusercontent.com/6528050/55360145-9226e080-54a1-11e9-90e5-d29c1fc2bcfc.png)

**Comment by yahehe** [comment]
If it helps, my `microcks.yml` contents are:
```
version: '2'
networks:
  main:
services:
  mongo:
    image: mongo:3.3.12
    container_name: microcks-mongo
    volumes:
      - "~/tmp/microcks-data:/data/db"
    networks:
      main:
        aliases:
          - mongo
  postman:
    image: microcks/microcks-postman-runtime:latest
    container_name: microcks-postman-runtime
    networks:
      main:
        aliases:
          - postman
  keycloak:
    image: jboss/keycloak:3.4.0.Final
    command: "-b 0.0.0.0 -Dkeycloak.import=/microcks-keycloak-config/microcks-realm-sample.json"
    container_name: microcks-keycloak
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak-realm:/microcks-keycloak-config
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "123"
    networks:
      main:
        aliases:
          - keycloak
  app:
    depends_on:
      - mongo
      - postman
      - keycloak
    image: microcks/microcks:latest
    container_name: microcks
    volumes:
      - ./config:/deployments/config
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=microcks
      - POSTMAN_RUNNER_URL=http://postman:3000
      - TEST_CALLBACK_URL=http://microcks:8080
      - KEYCLOAK_URL=http://docker.for.mac.localhost:8180/auth
    networks:
      main:
        aliases:
          - microcks
```
