### ISSUE TITLE
Problem with example formats causing issues between Apicurio and Microcks

### ISSUE THREAD

**Issue by crismarfr** [microcks/microcks#134]
Hi,
I use OPENAPI format and design my contract API with APICURIO. I define response example like this 👎 
```
[
    {
        "name": "some text",
        "year": 84,
        "model": "some text"
    },
    {
        "name": "some text",
        "year": 7,
        "model": "some text"
    }
]
```
But APICURIO translate this format like this : 
```
  examples:
                        laurent_cars:
                            value:
                                -
                                    name: some text
                                    year: 84
                                    model: some text
                                -
                                    name: some text
                                    year: 7
                                    model: some text
```

When i import contract (.yaml) in microcks, i have un issue and the response example doesn't exist in microcks. The example response in the format generate by apicurio, can't be integrate in microcks.
Can you explain this issue ?
Thank you 
Cordially

**Comment by lbroudoux** [comment]
Thank you for opening this issue serialization format of example seems to have changed in Apicurio. Evrrything was previously handled as string bu now it seems that exporter takes care of export format and align example format on this lattest.

**Comment by lbroudoux** [comment]
Independently from Apicurio, Microcks importer should be enhanced to support different example formats whatever may be the format of the whole OpenAPI contract.

That way, we should be able to handle as valid `ARRAY` representations:
```
examples:
  simple:
    value:
    - foo: some text
      bar: 11
   - foo: some text
      bar: 35
```
OR
```
"examples": {
   "simple": {
     "value": [
       {
         "foo": "some text",
         "bar": 11
       },
       {
         "foo": "some text",
         "bar": 35
       }
     ]
  }
}
```
OR
```
"examples": {
  "simple": {
    "value": "[\n    {\n        \"foo\": \"some text\",\n        \"bar\": 11\n    },\n    {\n        \"foo\": \"some text\",\n        \"bar\": 35\n    }\n]"
  }
}
```
OR
```
examples:
  simple:
    value: |-
                    [
                        {
                            "foo": "some text",
                            "bar": 11
                        },
                        {
                            "foo": "some text",
                            "bar": 35
                        }
                    ]
```

AND as valid `OBJECT` representations:
```
examples:
  single:
    value:
      foo: some text
      bar: 55
```
OR
```
"examples": {
  "single": {
    "value": {
      "foo": "some text",
      "bar": 55
    }
  }
}
```
OR
```
"examples": {
  "single": {
    "value": "{\n  \"foo\": \"some text\",\n  \"bar\": 55\n }"
  }
}
```
OR
```
examples:
  single:
    value: |-
                    {
                      "foo": "some text",
                      "bar": 55
                    }
```
