### ISSUE TITLE
External KeycloakX causing failed authentication

### ISSUE THREAD

**Issue by luisnarquel** [microcks/microcks#1340]
Hey!

I've been trying to make Microcks work with my existing instance of KeycloakX using the following helm chart

https://github.com/codecentric/helm-charts/tree/master/charts/keycloakx

I'm able to get to the first login page on Keycloak and input the admin/microcks123 credentials, but then i get "Failed to initialize authentication system"

I get no logs on both Microcks and Keycloak when this happens.

On my browser i can see that i get redirected to Keycloak:

https://keycloak.localdev.me/realms/microcks/protocol/openid-connect/auth?client_id=microcks-app-js&redirect_uri=https%3A%2F%2Fmicrocks.localdev.me%2F&state=42a3df29-66ca-40b8-bc8a-2e0ed402425a&response_mode=fragment&response_type=code&scope=openid&nonce=f52d3b28-38ff-45c0-9e0f-4dc75c511ccf

And then back to Microcks:

https://microcks.localdev.me/#state=42a3df29-66ca-40b8-bc8a-2e0ed402425a&session_state=4fb4ddea-e45c-4f0f-9fed-3bd295e9446e&iss=https%3A%2F%2Fkeycloak.localdev.me%2Frealms%2Fmicrocks&code=04f62a23-2534-49ec-9046-2a3a59647887.4fb4ddea-e45c-4f0f-9fed-3bd295e9446e.2a0c8aa9-7792-48ab-8709-5ac9c70739ef

I'm using the following values.yaml for Microcks:

```yaml
microcks:
  url: "microcks.localdev.me"
  ingressClassName: nginx
  logLevel: DEBUG
keycloak:
  enabled: true
  install: false
  url: "keycloak.localdev.me"
  privateUrl: http://keycloak-keycloakx-http.keycloak.svc.cluster.local:8080
  generateCert: true
```

Any idea what i might be missing?

**Comment by lbroudoux** [comment]
Hey @luisnarquel 
Have you check that your external Keycloak actually accepts connection via a `privateUrl`? This should be typically enabled using either `--hostname-strict-backchannel=true` (see https://www.keycloak.org/server/hostname-deprecated#_backend) or `--hostname-backchannel-dynamic true` (see https://www.keycloak.org/server/hostname#_utilizing_an_internal_url_for_communication_among_clients) depending on your Keycloak version.

**Comment by luisnarquel** [comment]
Hi @lbroudoux 

I wasn't using that setting, but after changing i'm still getting the same error.

This is my keycloak values.yaml

```yaml
ingress:
  enabled: true
  ingressClassName: nginx
  rules:
    - host: "keycloak.localdev.me"
      paths:
        - path: "/"
          pathType: "Prefix"
  tls: null
command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--features=token-exchange"
  - "--features=hostname:v2"
  - "--db=$(KC_DB)"
  - "--db-url-host=$(KC_DB_URL_HOST)"
  - "--db-url-database=$(KC_DB_URL_DATABASE)"
  - "--db-schema=$(KC_DB_SCHEMA)"
  - "--db-username=$(KC_DB_USER)"
  - "--db-password=$(KC_DB_PASSWORD)"
  - "--hostname=$(URL)"
  - "--http-enabled=true"
  - "--http-port=8080"
  - "--hostname-backchannel-dynamic=true"
extraEnv: |
  - name: URL
    value: http://keycloak.localdev.me
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: pass
  - name: KC_DB
    value: postgres
  - name: KC_DB_URL_HOST
    value: cluster.stackgres.svc.cluster.local
  - name: KC_DB_URL_DATABASE
    value: keycloak
  - name: KC_DB_SCHEMA
    value: keycloak
  - name: KC_DB_USER
    value: keycloak
  - name: KC_DB_PASSWORD
    value: pass
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_PROXY_HEADERS
    value: xforwarded
service:
  httpPort: 8080
http:
  relativePath: "/"
```

Thanks

**Comment by lbroudoux** [comment]
Have you tried with `--hostname-strict-backchannel=false? That's what we're using at the moment and it's working. It's deprecated but still ok.

Otherwise, have you seen anything in the Microcks pod logs? You may turn the log level to `DEBUG` to get more information.

**Comment by luisnarquel** [comment]
Added - "--hostname-strict=false" but still getting the same error.

I already have the logs set to debug:

```yaml
microcks:
  url: "microcks.localdev.me"
  ingressClassName: nginx
  logLevel: DEBUG
```

But the only logs that i'm getting on microcks are:

17:09:02.088 [DEBUG] io.github.microcks.web.KeycloakConfigController - Returning 'microcks' realm config, for https://keycloak.localdev.me
