### ISSUE TITLE
Using AWS Hosted MongoDB/DocumentDB with Microcks

### ISSUE THREAD

**Issue by kurst03** [microcks/microcks#1341]
I've successfully deployed Microcks in our EKS and configured it to use AWS Aurora (Postgres) for Keycloak. But I can't figure out how to configure Microcks to use AWS hosted MongoDB (or DocumentDB which is supposedly MongoDB compatible).

I've tried to override the connection string `SPRING_DATA_MONGODB_URI` to include the recommended parameters as per AWS guide:

```
mongodb://${SPRING_DATA_MONGODB_USER}:${SPRING_DATA_MONGODB_PASSWORD}@some-cluster-name.amazonaws.com:27017/${SPRING_DATA_MONGODB_DATABASE}?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
```

But AWS also requires me to provide `tlsCAFile=global-bundle.pem` as part of the connection string.

Is there a way I can override some values in Microcks's chart to achieve this? If not, how do I go about using external MongoDB instance with Microcks in general?

**Comment by lbroudoux** [comment]
Hi @kurst03,

The Helm chart provides a `mongodb.uriParameters` that allows you to provide extra parameters like `?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false`.

Regarding the `global-bundle.pem` file, you should be able to mount it as a Secret into the Microcks pod using the `microcks.customSecretRef` chart setting. This allows you to mount an arbitrary secret into `/deployments/config/custom/secret` path in the Microcks pod. You can then provide certificates for external Keycloak or MongoDB.

We don't have a guide on how to do that at the moment and we'd be more than happy to get your feedback (or notes) if it works on your side!

**Comment by kurst03** [comment]
Thanks @lbroudoux - trying this out now!

**Comment by kurst03** [comment]
So, I added `mongodb.uriParameters` as well as `mongodb.uri` to be something like:

```
microcks:
  url: microcks.<redacted>.com
  logLevel: DEBUG
  customSecretRef:
    secret: microcks-keystore
    key: cacerts

mongodb:
  install: false
  uri: "docdb-<redacted>.us-east-1.docdb.amazonaws.com:27017"
  uriParameters: "?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
  secretRef:
    secret: microcks-mongodb-secrets
    usernameKey: username
    passwordKey: password
    adminUsername: adminUsername
    adminPassword: adminPassword
```

And I can confirm that the app tried to connect to it by observing the logs:
```
18:33:39.387 [INFO] io.github.microcks.config.WebConfiguration - Web application fully configured                                                                                                                                         

18:33:39.537 [WARN] org.mongodb.driver.uri - Connection string contains unsupported option 'tlscafile'.                                                                                                                                   

18:33:39.550 [INFO] org.mongodb.driver.client - You appear to be connected to a DocumentDB cluster. For more information regarding feature compatibility and support please visit https://www.mongodb.com/supportability/documentdb
.... <redacted> ...
18:33:45.615 [INFO] org.mongodb.driver.cluster - No server chosen by ReadPreferenceServerSelector{readPreference=ReadPreference{name=secondaryPreferred, hedgeOptions=null}} from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=docdb-<redacted>.us-east-1.docdb.amazonaws.com:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
18:33:49.730 [INFO] org.mongodb.driver.cluster - Exception in monitor thread while connecting to server docdb-<redacted>.us-east-1.docdb.amazonaws.com:27017                                                com.mongodb.MongoSocketWriteException: Exception sending message        

```

I've also confirmed that the `global-bundle.pem` was imported on the secret that's referenced by the `customSecretRef`.

**Comment by kurst03** [comment]
The `values.yaml` from the microcks chart, states the following in the comment:
```
# Custom secret for Microcks
  # It can be usec to deploy a keystore to add certificats to trust sso connection with keycloak.
  # In this case: Use an existing secret with the provided keystore.
  # Don't forget to add java options like that if your secret is a keystore:
  # JAVA_OPTIONS: "-Djavax.net.ssl.trustStore=/deployments/config/custom/secret/KEYSTORE -Djavax.net.ssl.trustStorePassword=XXXXX"
```

Do I need to override that somewhere too in order for the above to work? Or there's a misconfiguration somewhere in my manifests?

**Comment by kurst03** [comment]
and if I looked at MongoDB [doc](https://www.mongodb.com/docs/v6.3/reference/connection-string/#std-label-connections-connection-options): `tlsCAFile` parameter is supported, but perhaps Microcks codebase parsed those as lowercase, hence the warning above?

```
18:33:39.537 [WARN] org.mongodb.driver.uri - Connection string contains unsupported option 'tlscafile'.                                                                                                                                   
```

**Comment by lbroudoux** [comment]
Hi @kurst03,

Thanks for the explanations. As said before, I have never done this setup, but it's nice learning together.

The Microcks code base does not manipulate connection string and reuses Spring Data MongoDB for connection. It appears that all the connection string handling is directly delegated to the MongoDB Java Driver.

From what we can read in its [connection string documentation](https://www.mongodb.com/docs/manual/reference/connection-string-options/#std-label-connections-connection-options) it looks like `tlsCAFile` is `[..] is not supported by all drivers. Refer to the [Drivers](https://www.mongodb.com/docs/drivers/) documentation.`. So when looking at the Java Driver documentation [on TLS here](https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/connection/tls/#std-label-tls-ssl), the recommended way of providing a CA certificate seems to use the standard JVM `Trust Store`.

So my guess would be to try those things:
* Retrieve the CA cert and put it into a Trust store using the `keytool` utility
* Then, store this trust store into the Kubernetes Secret you'll reference in `microcks.customSecretRef` prop
* Then actually add the `JAVA_OPTIONS: "-Djavax.net.ssl.trustStore=/deployments/config/custom/secret/TRUSSTORE -Djavax.net.ssl.trustStorePassword=XXXXX"` env variable to load this trust store at the JVM level
* Remove the `tlsCAFile=global-bundle.pem` option the connection string as it looks it is not used by the driver that relies on JVM's loaded trust store.

Let us know how things are going!

**Comment by kurst03** [comment]
> As said before, I have never done this setup, but it's nice learning together.
@lbroudoux for sure! Happy to document this eventually if I get it to work. Will try your suggestions above. Thanks!

**Comment by kurst03** [comment]
@lbroudoux so I had to disable the TLS for now to move forward with my deployment. Good news is Microcks can be used with AWS DocumentDB (MongoDB compatible) and AWS RDS (Postgres).

I will come back to this again in a few. Feel free to resolve/close and I can re-open when I get to it in couple days.

**Comment by mondrias** [comment]
Hello friends, sorry for the translation, on this side we were able to connect via SSL with an AWS DocumentDB. The following repository helped us [spring-boot-aws-docdb-example](https://github.com/hungbang/spring-boot-aws-docdb-example).

Specifically, the script:
- `./generateKeyStore-linux.sh`
- `./generateKeyStore-macos.sh`

I change the script URL to:
```bash
curl -sS https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem

- The secret was created in Kubernetes:

kubectl create secret generic microks-documentdb-tls-secret --from-file=rds-truststore.jks -n microcks

<resource "kubernetes_secret" "documentdb_tls_secret" {
  metadata {
    name = "${local.namespace_microcks}-documentdb-tls-secret"
    namespace = local.namespace_microcks  # O el namespace en el que estés trabajando
  }

  binary_data = {
    "rds-truststore.jks" = filebase64("${path.module}/certs/rds-truststore.jks")
  }

  type = "Opaque"
  depends_on = [module.aws_eks_teams_microcks[0]]
}>


- In values.yaml
JAVA_OPTIONS: "-Djavax.net.ssl.trustStore=/deployments/config/custom/secret/rds-truststore.jks -Djavax.net.ssl.trustStorePassword=mongodb -Djavax.net.ssl.keyStoreType=JKS"
  customSecretRef:
    secret: microcks-documentdb-tls-secret
    key: rds-truststore.jks

The detail is that when downloading the Helm chart it does not take the value JAVA_OPTIONS:

<img width="1172" alt="Image" src="https://github.com/user-attachments/assets/b9f84ded-e3cd-4459-aa6f-de7b9faf5719" />


**- so I modified it to test the deployment by hand**

<img width="1018" alt="Image" src="https://github.com/user-attachments/assets/b8df0c64-934a-4fe0-8c77-46b2d6b14442" />

**- with a successful result**

<img width="1666" alt="Image" src="https://github.com/user-attachments/assets/482a810e-2dd3-4634-8022-8f5c0a358e58" />

<img width="1657" alt="Image" src="https://github.com/user-attachments/assets/dc38b212-4138-4fdb-b235-18ad1bdcc284" />

I ask for help in modifying the helm chart while I am going to have it modified locally.

The conexion to db
mongodb:
  install: false
  uri: ".docdb.amazonaws.com:27017"
  uriParameters: "?tls=true&tlsCAFile=/deployments/config/custom/secret/global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
  secretRef:
    secret: microcks-mongodb-secrets
    usernameKey: username
    passwordKey: password

**Comment by yada** [comment]
Hi @kurst03 and @mondrias ,
Thank you for sharing your feedback on this point. Would you be willing to contribute to the community effort to document this? See: https://github.com/microcks/community/tree/main/install/%20%20aws @alikhere and @Vaishnav88sk will be happy to have your inputs and collaboration regarding the mentee work in progress they are doing as part of the LFX mentorship program 🙌

**Comment by kurst03** [comment]
@yada of course.

**Comment by Vaishnav88sk** [comment]
Hello @kurst03 , @mondrias ,

While attempting to connect the Microcks Container to AWS DocumentDB, I encountered the following error:
```sh
Exception in monitor thread while connecting to server microcks-docdb-instance.cza0gcu8ejq5.ap-south-1.docdb.amazonaws.com:27017
com.mongodb.MongoSocketWriteException: Exception sending message
...
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: 
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
...
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
...
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:383)
	... 29 common frames omitted
```

Here is the values.yaml file I am using for overriding Microcks chart values:
```yaml
appName: microcks
ingresses: true

microcks:
  url: microcks.local
  ingressClassName: nginx
  ingressAnnotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
   
  grpcEnableTLS: true
  grpcIngressClassName: nginx
  grpcIngressAnnotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    
  env:
    - name: SPRING_DATA_MONGODB_URI
      value: "mongodb://<username>:<password>@microcks-docdb-instance.<docdb number>.ap-south-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&retryWrites=false"
    - name: CORS_REST_ALLOWED_ORIGINS
      value: "https://keycloak.43.204.192.72.nip.io"
    - name: CORS_REST_ALLOW_CREDENTIALS
      value: "true"    

keycloak:
  enabled: true
  install: false
  url: keycloak.43.204.192.72.nip.io
  privateUrl: https://keycloak.43.204.192.72.nip.io
  realm: microcks
  client:
    id: microcks-app-js
    secret: microcks123

mongodb:
  install: false  
  database: microcks
  secretRef:
    secret: microcks-mongodb-connection
    usernameKey: username
    passwordKey: password
    
ingress:
  enabled: true
  tls: true

``` 
Based on your experience with the issue, how can I resolve it?

**Comment by mondrias** [comment]
@Vaishnav88sk Hi, just to confirm — are you deploying to Kubernetes on EKS? For now, I recommend not enabling the ingress, so we can focus solely on establishing the connection to DocumentDB. Could you please share the section where the secret containing the JKS is mounted? Also, were you able to generate the JKS using the script?

> Hello [@kurst03](https://github.com/kurst03) , [@mondrias](https://github.com/mondrias) ,
> 
> While attempting to connect the Microcks Container to AWS DocumentDB, I encountered the following error:
> 
> Exception in monitor thread while connecting to server microcks-docdb-instance.cza0gcu8ejq5.ap-south-1.docdb.amazonaws.com:27017
> com.mongodb.MongoSocketWriteException: Exception sending message
> ...
> Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: 
> sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> ...
> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> ...
> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
> 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
> 	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
> 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:383)
> 	... 29 common frames omitted
> Here is the values.yaml file I am using for overriding Microcks chart values:
> 
> appName: microcks
> ingresses: true
> 
> microcks:
>   url: microcks.local
>   ingressClassName: nginx
>   ingressAnnotations:
>     cert-manager.io/cluster-issuer: "letsencrypt-prod"
>     nginx.ingress.kubernetes.io/proxy-body-size: "50m"
>    
>   grpcEnableTLS: true
>   grpcIngressClassName: nginx
>   grpcIngressAnnotations:
>     cert-manager.io/cluster-issuer: "letsencrypt-prod"
>     nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
>     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
>     
>   env:
>     - name: SPRING_DATA_MONGODB_URI
>       value: "mongodb://<username>:<password>@microcks-docdb-instance.<docdb number>.ap-south-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&retryWrites=false"
>     - name: CORS_REST_ALLOWED_ORIGINS
>       value: "https://keycloak.43.204.192.72.nip.io"
>     - name: CORS_REST_ALLOW_CREDENTIALS
>       value: "true"    
> 
> keycloak:
>   enabled: true
>   install: false
>   url: keycloak.43.204.192.72.nip.io
>   privateUrl: https://keycloak.43.204.192.72.nip.io
>   realm: microcks
>   client:
>     id: microcks-app-js
>     secret: microcks123
> 
> mongodb:
>   install: false  
>   database: microcks
>   secretRef:
>     secret: microcks-mongodb-connection
>     usernameKey: username
>     passwordKey: password
>     
> ingress:
>   enabled: true
>   tls: true
> Based on your experience with the issue, how can I resolve it?

**Comment by Vaishnav88sk** [comment]
> [@Vaishnav88sk](https://github.com/Vaishnav88sk) Hi, just to confirm — are you deploying to Kubernetes on EKS? For now, I recommend not enabling the ingress, so we can focus solely on establishing the connection to DocumentDB. Could you please share the section where the secret containing the JKS is mounted? Also, were you able to generate the JKS using the script?
> 
> > Hello [@kurst03](https://github.com/kurst03) , [@mondrias](https://github.com/mondrias) ,
> > While attempting to connect the Microcks Container to AWS DocumentDB, I encountered the following error:
> > Exception in monitor thread while connecting to server microcks-docdb-instance.cza0gcu8ejq5.ap-south-1.docdb.amazonaws.com:27017
> > com.mongodb.MongoSocketWriteException: Exception sending message
> > ...
> > Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed:
> > sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> > ...
> > Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> > ...
> > Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> > at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
> > at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
> > at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
> > at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:383)
> > ... 29 common frames omitted
> > Here is the values.yaml file I am using for overriding Microcks chart values:
> > appName: microcks
> > ingresses: true
> > microcks:
> > url: microcks.local
> > ingressClassName: nginx
> > ingressAnnotations:
> > cert-manager.io/cluster-issuer: "letsencrypt-prod"
> > nginx.ingress.kubernetes.io/proxy-body-size: "50m"
> > grpcEnableTLS: true
> > grpcIngressClassName: nginx
> > grpcIngressAnnotations:
> > cert-manager.io/cluster-issuer: "letsencrypt-prod"
> > nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
> > nginx.ingress.kubernetes.io/ssl-passthrough: "true"
> > env:
> > - name: SPRING_DATA_MONGODB_URI
> > value: "mongodb://:@microcks-docdb-instance..ap-south-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&retryWrites=false"
> > - name: CORS_REST_ALLOWED_ORIGINS
> > value: "https://keycloak.43.204.192.72.nip.io"
> > - name: CORS_REST_ALLOW_CREDENTIALS
> > value: "true"
> > keycloak:
> > enabled: true
> > install: false
> > url: keycloak.43.204.192.72.nip.io
> > privateUrl: https://keycloak.43.204.192.72.nip.io
> > realm: microcks
> > client:
> > id: microcks-app-js
> > secret: microcks123
> > mongodb:
> > install: false
> > database: microcks
> > secretRef:
> > secret: microcks-mongodb-connection
> > usernameKey: username
> > passwordKey: password
> > ingress:
> > enabled: true
> > tls: true
> > Based on your experience with the issue, how can I resolve it?

Yes, I am deploying on EKS, and I am generating the JKS using the script. I will disable the ingress for now and share the section where the JKS is mounted as a Kubernetes secret.

**Comment by mondrias** [comment]
@Vaishnav88sk  
I understand, my friend. I don't have a computer nearby right now; I'm replying from my phone. In about an hour, as soon as I have access to a computer, I can send you the example of the ingress for AWS and the connection details for DocumentDB. You might also need to modify the Helm chart (if it hasn't been modified yet) to specify the JKS file to use in the JAVA_OPTS variable.

> 

<img width="1018" alt="Image" src="https://github.com/user-attachments/assets/e9077ac0-0b9e-4a42-b352-3513a479678f" />

**Comment by kurst03** [comment]
@Vaishnav88sk @mondrias 

Our self-hosted Microcks instance in EKS is setup to connect to DocumentDB and the only thing we configured in our `values.yaml` relevant to the mongodb setup is just like this
```
mongodb:
  install: false
  uri: "foo-bar-derp-glorp.some-aws-region.docdb.amazonaws.com:27017"
  uriParameters: "?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
  secretRef:
    secret: your-secret-ref-name
    usernameKey: your-user-name-key
    passwordKey: your-password-key
    adminUsername: your-admin-username
    adminPassword: your-admin-password
```
