### ISSUE TITLE
APIExample import not setting expected status code in Mock / Test Response.

### ISSUE THREAD

**Issue by ZePirateDude** [microcks/microcks#1365]
### Describe the bug

Hello everyone !

I encountered an issue while experimenting with the API Examples Format feature. ([link](https://microcks.io/documentation/references/examples/))
It seems the expected status code is not set in the mock response.
While the mock works as intended and return a 200 status code, I get an error when I start a test run with a OpenAPI schema runner. 
As an example, here are my openapi.yml and APIExample.yml files : [test.zip](https://github.com/user-attachments/files/17294176/test.zip)

openapi.yml : 
```
...
paths:
  /pets:
    post:
      tags:
        - Pets
      summary: Register a pet
      operationId: registerPet
      requestBody:
        description: Pet to register
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
...
``` 

APIExample.yml :
```
...
operations:
  'POST /pets':
    Test 1:
      request:
        body:
          age: 1
          name: "Rantanplan"
          birthDate: "2023-10-03"
          species: "Dog"
        headers:
          Accept: application/json
      response:
        code: '200'
        mediaType: application/json
        body:
          age: 1
          name: "Rantanplan"
          birthDate: "2023-10-03"
          species: "Dog"
    Test 2:
      request:
        body:
          age: 0
          name: "Médor"
          birthDate: "2024-10-03"
          species: "Dog"
        headers:
          Accept: application/json
      response:
        code: '200'
        mediaType: application/json
        body:
          age: 0
          name: "Médor"
          birthDate: "2024-10-03"
          species: "Dog"
...
```

When both file are imported, the status code is not set for the mock response :
![mock_error](https://github.com/user-attachments/assets/339a0a38-43cb-4e2d-8461-22a8fdd9f797)

When I run the tests, I get this error :
![test_error](https://github.com/user-attachments/assets/279bd27e-fec1-4a13-95cb-864ad4b31bee)
 
I tried using an Integer instead for a string for the code declaration. I also tried not declaring a status code since the documentation hint at 200 being the default case.

I'm using the microcks-uber:1.10.1-native as described in the quickstart guide, with Docker on WSL.

As the server app, I used a simple Springboot application and generate the interface with the Spring OpenAPI Generator.
I use this very simple implementation :

```java
@RestController
@RequestMapping("/")
public class PetsApiImpl implements PetsApi {

    @Override
    public ResponseEntity<Pet> registerPet(Pet pet) {
        return new ResponseEntity<>(pet, HttpStatus.OK);
    }
}
``` 

### Expected behavior

The test runner expect a 200 status code in the response and the test succeed. 

### Actual behavior

The test runner expect a 'null' status code in the response, and the test fails
![test_error](https://github.com/user-attachments/assets/d2864072-720d-4625-8fe5-679cfbfd258b)

### How to Reproduce?

1. Start Microcks as described in the quickstart guide : `docker run -p 8585:8080 -it --rm quay.io/microcks/microcks-uber:latest-native`
2. Import the openapi.yml file as a main artefact
3. Import the APIExample.yml file as a secondary artefact
4. Check the mock response status code in the Services & APIs menu
5. Start the java application server
6. Launch a test with a OPEN API SCHEMA runner with the java application endpoint
7. Examine the test failure

### Microcks version or git rev

microcks-uber:1.10.1-native

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker run as described in the Quickstart guide.
