### ISSUE TITLE
Applying constraints to REST mocks

### ISSUE THREAD

**Issue by mikeswiss** [microcks/microcks#1366]
### Reason/Context

Teams would like to be able to configure constraints via OAS file.  

Right now this is possible with an additional APIMetadata artifact following the lovely guide https://microcks.io/documentation/references/metadada/

But if possible it would be nice to  get the information from the spec.`

### Description

As of today, the required: true in OpenAPI spec is not translated into Parameter constraints on mocks. We just use them to infer default dispatching rules. The idea at first was to get this translation and allow finer management via APIMetadata

### Implementation ideas

```
parameters:
      
name: organization
       in: query
       required: true
        schema:
             type: string
              example: "wbd-streaming"
name: repository
      in: query
      required: true
      schema:
            type: string
            example: "test-repo"
```
