### ISSUE TITLE
APIExample doesn't provide a default `status`

### ISSUE THREAD

**Issue by kaos** [microcks/microcks#1439]
### Describe the bug

Import an `APIExample` with no `status` declared in the example response.

### Expected behavior

Microcks should default to expect a `200` OK status.

### Actual behavior

Microcks expects a `null` status.

### How to Reproduce?

```yaml
$schema: https://microcks.io/schemas/APIExamples-v1alpha1-schema.json
apiVersion: mocks.microcks.io/v1alpha1
kind: APIExamples
metadata:
  name: Calc
  version: 1.0
operations:
  'GET /calc/add/{lhs}/{rhs}':
    One and one:
      request:
        parameters:
          lhs: 1
          rhs: 1
      response:
        mediaType: application/json
        body:
          result: 2
```

### Microcks version or git rev

1.11.0-SNAPSHOT

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker run --name microcks --pull always -p 8585:8080 -d quay.io/microcks/microcks-uber:nightly-native-arm64

### Additional information

https://discord.com/channels/1162356525969449100/1162356526468575274/1314145185214627880
