### ISSUE TITLE
explode: true with style: deepObject in query parameter is neglected

### ISSUE THREAD

**Issue by denrolya** [microcks/microcks#154]
Having this url `http://localhost:8080/rest/xxx/1.0.0/api/v1/some/url?filter[some_param]=yes`, I am describing it's `filter` query parameter in OpenAPI documentation as follows:
```
- in: query
  name: filter
  description: Array of filters
  required: false
  style: deepObject
  explode: true
  schema:
    type: object
    properties:
      some_param:
        type: array
        items:
          type: string
          enum: ['yes', 'no']
```
And i get the correct result when look in SwaggerUI, unfortunately in Microcks I see following:  `http://localhost:8080/rest/xxx/1.0.0/api/v1/some/url/filter={"some_param":"yes"}`.
