### ISSUE TITLE
Allow to configure AI Copilot OpenAI endpoint when install via Helm

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1547]
### Reason/Context

As of today, the `OpenAICopilot` accepts an `api-url` configuration property to specify the API endpoint to use (default is https://api.openai.com/). However, setting a value to this property is not available when using the Helm chart for deployment.

### Description

We should allow a new `apiUrl` property (next to `apiKey`) in OpenAI configuration block:

```yaml
features:
  # [...]
  # AI Copilot configuration properties
  aiCopilot:
    enabled: true
    implementation: openai

    openai:
      apiKey: <sk-my-openai-api-token>
      timeout: 20
      model: gpt-3.5-turbo
      maxTokens: 2000
```

### Implementation ideas

See above.
