### ISSUE TITLE
AICopilot mistakes when computing dispatch criteria with URI elements

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1595]
### Describe the bug

When using the AICopilot with an API using a `URI_ELEMENTS` dispatcher, the `dispatchCriteria` attached to a generated response may be badly computed.

Imagine an AI Copilot suggestion like this one:
```yaml
- example: 1
  request:
    url: /customer/12345/accounts?filter=portfolio
    headers:
      accept: application/json
    parameters:
      customerId: 12345
      filter: portfolio
    body:
  response:
    code: 200
    headers:
      content-type: application/json
    body:
      id: 12345-portfolio
      description: "Portfolio account"
```

corresponding to a `GET /customer/{customerId}/accounts` operation and having a `URI_ELEMENTS` dispatcher with the `customerId ?? filter` dispatching rules.

### Expected behavior

Computed dispatch criteria for this response must be `/customerId=12345?filter=portfolio`.

### Actual behavior

However, AI Copilot compute something like `?customerId=12345filter=portfolio/customerId=12345/filter=portfolio`. As a consequence, the mock cannot work when the import is finalised in Microcks.

### How to Reproduce?

See full description above.

### Microcks version or git rev

nightly

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

all

### Additional information

Bug is there from the beginning of AI Copilot introduction.
