### ISSUE TITLE
Regression: AI Copilot sample export to APIExamples format generates empty file on nightly build

### ISSUE THREAD

**Issue by yada** [microcks/microcks#1601]
I noticed a regression affecting the AI Copilot feature on the nightly build. When attempting to export generated samples to the APIExamples format, the system produces an empty file.

✅ Expected Behavior
The export should generate a populated APIExamples file as it does on version 1.11.2.

❌ Current Behavior
An empty file is generated during export. Ex:
```
apiVersion: mocks.microcks.io/v1alpha1
kind: APIExamples
metadata:
  name: API Pastries
  version: 0.0.1
operations: {}
```

🧪 Steps to Reproduce

1. Use AI Copilot to generate examples from a spec
3. Attempt to export the result to APIExamples format
5. Observe that the resulting file is empty

✅ Works on:
v1.11.2 — export is successful and the file contains examples

❌ Fails on:
Nightly build version:
```
Version 1.12.0-SNAPSHOT
Build timestamp 2025-05-07T09:42:19Z
```
