### ISSUE TITLE
V1.2.0: Cant reach keycloak on authentication

### ISSUE THREAD

**Issue by TamimiGitHub** [microcks/microcks#354]
## Problem

I am just [getting started](https://microcks.io/documentation/getting-started/) with microcks v1.2.0 for evaluation. After cloning and starting up the docker image 
```
cd microcks/install/docker-compose
docker-compose up -d
```
I get the following error when I attempt to navigate to localhost:8080
<img width="1543" alt="Screen Shot 2021-02-25 at 6 27 06 PM" src="https://user-images.githubusercontent.com/6826053/109233224-7fa1a880-7797-11eb-99a9-718477e8de34.png">

This is my docker-compose file

```
version: '2'

services:
  mongo:
    image: mongo:3.4.23
    container_name: microcks-db
    volumes:
      - "~/tmp/microcks-data:/data/db"

  keycloak:
    image: jboss/keycloak:10.0.1
    container_name: microcks-sso
    ports:
      - "18080:8080"
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_IMPORT: "/tmp/microcks-realm.json"
      KEYCLOAK_FRONTEND_URL: "http://localhost:18080/auth"
    volumes: 
      - "./keycloak-realm/microcks-realm-sample.json:/tmp/microcks-realm.json"

  postman:
    image: quay.io/microcks/microcks-postman-runtime:latest
    container_name: microcks-postman-runtime

  app:
    depends_on:
      - mongo
      - keycloak
      - postman
    image: quay.io/microcks/microcks:latest
    container_name: microcks
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=microcks
      - POSTMAN_RUNNER_URL=http://postman:3000
      - TEST_CALLBACK_URL=http://microcks:8080
      - SERVICES_UPDATE_INTERVAL=0 0 0/2 * * *
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_PUBLIC_URL=http://localhost:18080/auth

```

Not sure if there are any particular ports that needs to be exposed? 

## Environment
MacOS Catalina

Any directions or idea on what the problem might be? Thanks!
