### ISSUE TITLE
Implement AsyncAPI restriction on message examples

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#385]
As per [AsyncAPI website documentation](https://www.asyncapi.com/docs/specifications/2.0.0#messageObject), `examples` in Message object are:

> `[Map[string, any]]` - An array with examples of valid message objects.

However, in current tooling - validator, documentation generator and the AsyncAPI playground namely - the implementation is following the specification file find in [GitHub master branch](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#messageObject). There the definition of `examples` is a bit different:

> `[Map[string, any]]` - An array of key/value pairs where keys MUST be either **headers** and/or **payload**. Values MUST contain examples that validate against the headers or payload fields, respectively.

Moreover, tooling does not accept any additional properties at the moment (see https://github.com/asyncapi/asyncapi-node/blob/0e01a075b8103ceee66a8f142799c21fcb6dd06d/schemas/2.0.0.json#L704)

Following the AsyncAPI website documentation, Microcks convention of specifying examples with a key that is used as a name is valid:

```yaml
examples:
  - laurent:
      summary: Example for Laurent user
      headers: |-
        {"my-app-header": 23, "sentAt": "2020-03-11T08:03:28Z"}
      payload: |-
        {"fullName": "Laurent Broudoux", "email": "laurent@microcks.io", "age": 41}
```

But following current tooling and GItHub master branch it is not and should be specified now as:

```yaml
examples:
  - headers:
      my-app-header: 23
      sentAt: "2020-03-11T08:03:28Z"
    payload: |-
      {"fullName": "Laurent Broudoux", "email": "laurent@microcks.io", "age": 41}
```

We are loosing here the ability to specify a meaningful name. 

A Feature Request exists in AsyncAPI to allow more elaborate way of specifying examples (see https://github.com/asyncapi/spec/issues/329). Hope to have some time soon to tackle this one. Vote for it if you support it ;-)

In the meantime, we are going to implement fallback for those who'd prefer sticking with the specification as in GitHub master branch and current tooling.
