### ISSUE TITLE
AsyncAPI tests fail when examples have escaped quotes

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#388]
When serialized to `microcks-async-minion` for launching a new test, examples that are already escaped like:

```yaml
        examples:
          - laurent:
              summary: Example for Laurent user
              headers: "{\"my-app-header\": 23}"
```

are escaped one more time and results in:

```yaml
        examples:
          - laurent:
              summary: Example for Laurent user
              headers: \"{\\"my-app-header\\": 23}\"
```

This makes the spec un-parseable with errors like:

```
com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: mapping values are not allowed here
 in 'reader', line 38, column 46:
     ...  headers: \"{\\"my-app-header\\": 23}\"
```

This then lead to #389
