### ISSUE TITLE
[FEATURE] Add random mock sample by value list

### ISSUE THREAD

**Issue by manuel-padovani** [microcks/microcks#599]
Hello, Would be great if will be possibile to use a syntax to generate mock chossing between a list of values like this:

        examples:
          - name: sample
            payload:
              value: '{{ randomValue(["myval1", "myval2", "myval3"]) }}'
              timeStamp: '{{ now() }}'

I have many use case that require this features.

**Comment by lbroudoux** [comment]
Hey @manuel-padovani!

Thanks for the suggestion, this is a great idea!

**Comment by lbroudoux** [comment]
In order to fit in the actual templating engine, the syntax will be like:

```yaml
    examples:
      - name: sample
        payload:
          value: '{{ randomValue(myval1, myval2, myval3) }}'
          timeStamp: '{{ now() }}'
```
