### ISSUE TITLE
Set dynamic parameters

### ISSUE THREAD

**Issue by mflasquin** [microcks/microcks#632]
Hi,
Is it possible to define dynamic parameters like this :

```
      parameters:
        - name: id
          in: path
          description: Contact id
          required: true
          schema:
            type: integer
            format: int64
          examples:
              get-1761114:
                  value: "{{ randomInt(5,10) }}"
```
