### ISSUE TITLE
Wrong response using hyphen in query param & variable reference expression

### ISSUE THREAD

**Issue by dorianbrun** [microcks/microcks#653]
Hi, 
I'm facing a new issue when I use an hyphen in a query param and try to retrieve this value with variable reference expressions.

I have one operation like this :
**GET /users** which can use query params like "id" or "account-name".

I add two response examples in my openapi yaml file :
```
examples:
  get-users-id-10:
    value:
      id: "{{request.params[id]}}"
      accountName: "test"
  get-users-account-name-test:
    value:
      id: "8"
      accountName: "{{request.params[account-name]}}"
``` 

When I acces to http://localhost:8080/rest/Test/1.3.0/users?id=10 I get a correct response : 
`{"id":"10","accountName":"test"}`

But when I try http://localhost:8080/rest/Test/1.3.0/users?account-name=test I do not retrieve my "account-name" param value as a string but get it as an object and I do not understand why.
`{"id":"8","accountName":"{account-name=test}]}}"}`

How can I get this kind of response ? :
`{"id":"8","accountName":"test"}`

Thanks
