### ISSUE TITLE
Allow addition of extra config properties in main pod 

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#698]
This is a slight refactoring on top of #671 to avoid relying on external YAML file for additional Spring Boot properties to inject into new `extra` profile. You can now specify something like in your `values.yaml` file:

```yaml
  extraProperties:
    server:
      tomcat:
        remoteip:
          internal-proxies: 172.16.0.0/12
```

This will create another `application-extra.yml` file into the Microcks ConfigMap and append the `,extra` profile to the regular `prod` profile we use on Microcks Spring Boot component.
