### ISSUE TITLE
Keycloak container is failed to start in openshift

### ISSUE THREAD

**Issue by aniketvsawant** [microcks/microcks#70]
Hi Team,

I am trying to do the openshift deployment and seems like issue is with microcks-keycloak container. Remaining 4 containers are successfully deployed without any issue. Pod is not at all coming up and continuously failing with "Init Crash Loop Back-off" status. Does anyone facing any issue ?
I am doing deployment with ephemeral openshift template file. Please let me know.

It seems that issue is with initContainer.

    initContainers:
        - name: openshift-ca-pemtokeystore
          image: syndesisio/pemtokeystore:v0.2.1
          imagePullPolicy: IfNotPresent
          args:
          - "-keystore"
          - "/tls-keystore/openshift-truststore.jks"
          - "-ca-file"
          - "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          - "-ca-file"
          - "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
          volumeMounts:
          - name: "${APP_NAME}-keycloak-tls"
            mountPath: "/tls-keystore"
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 200Mi

Thanks.

**Comment by yoadmike** [comment]
Hi aniket , how did you overcome this? , (even a user mistake is good knowledge )

**Comment by aniketvsawant** [comment]
The issue was with init container. The init container is called “pem to keystore”, and its function is to take a PEM file and convert it to a keystore.  This container preps a keystore to be used by keycloak-server container.

As I am using on-premise enterprise openshift for deployment, the enterprise ca ans service-ca certificates are used but this pemtokeystore  didnt liked the ca.crt.  This is what output init-container was spitting when I tried and ran the pemtokeystore binary with those arguments. Since the init container was failing, keycloak-server container didn't proceed to start.  

```
[root@nocsst-dock ~]# docker run -ti --privileged -v /root/microcks/:/var/run/secrets/kubernetes.io/serviceaccount --entrypoint '/bin/sh' docker-registry-company.com/microcks/pemtokeystore:v0.2.1
/ # ./pemtokeystore -keystore /openshift-truststore.jks -ca-file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -ca-file /var/run/secrets/kubernetes.io/servi
ceaccount/service-ca.crt
Failed to create keystore: missing cn in CA certificate subject: {[US] [Company Name] [] [] [] [] []   [{2.5.4.6 US} {2.5.4.10 Company Name}] []}
```

One of those empty []’s should have the CN in it, but our enterprise ca cert doesn’t provide that.  This is an exception being thrown by the pemtokeystore application.  This is a bug that i am going to be reported to pemtokeystore team to resolve.  CN isn’t required for CA Certs.

I fixed this bug with some work around. Created a new ca cert file secret for this solution, where I removed the enterprise ca certs from it.  I’ve mounted it in /opt/pems/, and reconfigured the arguments I’ve passing to your keycloak init container.

```
initContainers:
    - name: openshift-ca-pemtokeystore
      image: syndesisio/pemtokeystore:v0.2.1
      imagePullPolicy: IfNotPresent
      args:
      - "-keystore"
      - "/tls-keystore/openshift-truststore.jks"
      - "-ca-file"
      - "/opt/pems/ca.crt"
      - "-ca-file"
      - "/opt/pems/service-ca.crt"
      volumeMounts:
      - name: "${APP_NAME}-keycloak-tls"
        mountPath: "/tls-keystore"
      resources:
        limits:
          memory: 512Mi
        requests:
          memory: 200Mi
```

Secret : microcks-tls
```
apiVersion: v1
data:
  ca.crt: >-
    xxxxxxxxx
  service-ca.crt: >-
    xxxxxxxxxx
kind: Secret
metadata:
  name: microcks-tls
  namespace: microcks
type: Opaque
```

Note : I have specified secret type = Opaque because I do not want validation, which means the secret does not claim to conform to any convention for key names or values.
