### ISSUE TITLE
Change in the config map does not trigger redeployment

### ISSUE THREAD

**Issue by sbr82** [microcks/microcks#823]
### Describe the bug

Changes in the values.yaml that are reflected on the microcks config map do not trigger redeployment. This is a problem for gitops environment, where a redeployment is triggered only by change of configuration.
Here there are useful tips on how to implement this:
https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

### Expected behavior

Change in the values.yaml that is changing the microcks config, for example:
```
features:
  repositoryFilter:
    enabled: true
    labelKey: domain
    labelLabel: Domain
    labelList: domain,status,type,tenant
```
should trigger redeployment.

### Actual behavior

the config map is changed, but there is no redeployment happening, one has to manually do a redeploy so that the config map changes are reflected.

### Microcks version or git rev

1.7.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

helm-chart
