### ISSUE TITLE
microcks UI not working when installed on Kind cluster on macOS

### ISSUE THREAD

**Issue by danapr** [microcks/microcks#860]
### Describe the bug

Hi!
I am trying to work with Microcks on a `kind` cluster, installing using helm on MacOS (i7). When trying to access the Microcks UI using Chrome I get a white screen. When sending a GET request to the same Microcks endpoint via postman I get 200 in response code, with a java script in the response's body, meaning the service is up and running, but the browser fails to load the UI.

More details:
Installation commands:
tried both:
`helm install microcks microcks/microcks --namespace=microcks --set appName=microcks --set features.async.enabled=true --set microcks.url=microcks.<kind_control_plane_ip>.nip.io --set keycloak.url=keycloak.<kind_control_plane_ip>.nip.io`
and a simple:
`helm install microcks microcks/microcks --namespace=microcks `
Both led to the same outcome.

For request forwarding:
Tried two options, and got different responses: 
1. `kubectl proxy`: when trying to access http://localhost:8001/api/v1/namespaces/microcks/services/microcks:8080/proxy/ the browser's console shows: 

- ```Failed to load resource: the server responded with a status of 404 (Not Found)```
- 
  ```
  [Microcks launch] Error while fetching Keycloak config: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404}

- 
  ```
  Uncaught {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404}

2. `kubectl port-forward service/microcks 8080:8080 -n microcks` : when trying to access 127.0.0.1:8080 the browser's console shows: 

- `[Microcks launch] Keycloak is enabled, launching OIDC login flow...`
- `crbug/1173575, non-JS module files deprecated.`

Thank you!

### Microcks version or git rev

helm chart

**Comment by lbroudoux** [comment]
Hey @danapr,
I think this is due to the kube proxy usage. I used to get through full-blown ingress and ingress-controller using Nginx. As Microcks access is secured using OIDC Authorization code flow, your browser will try redirect you to the `keycloak.<kind_control_plane_ip>.nip.io` you've set up. Don't know how it goes though when used via kube proxy...

**Comment by danapr** [comment]
I also tried without setting the specific url for `keycloak`, but still didn't work. Would assume that since both `microcks` and `keycloak` are within the cluster, so it should work.
Also, any ideas for the `kubectl port-forward` direction?

**Comment by danapr** [comment]
Any advice here?
This didn't work even without setting up `keycloak.<kind_control_plane_ip>.nip.io`. Why isn't it working with proxy?
Or can you share the Values.yml with Nginx as ingress controller instead?

**Comment by yada** [comment]
@danapr, we have not tested a Microcks installation on kind so far. 

If you are looking for a quick and easy Microcks test-drive on MacOS, please check our Docker Desktop Extension:
https://microcks.io/documentation/installing/docker-desktop-extension/

I just pushed a Microk8s community addon contribution: https://github.com/canonical/microk8s-community-addons/pull/155
So will see if we can find some time on kind... It will be great if you can contribute to this topic and document it if you make it work ;-) Keep us posted.

Regarding values, you can download the latest helm chart here: https://microcks.io/helm/microcks-1.7.1.tgz
and check "templates/ingress.yaml" :
```                                                                                  
{{- if .Values.ingresses -}}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Values.appName }}"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  {{- with .Values.microcks.ingressAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: "{{ .Values.appName }}"
    group: microcks
spec:
  tls:
  - hosts:
    - "{{ .Values.microcks.url }}"
    secretName: {{ .Values.microcks.ingressSecretRef | default (print .Values.appName "-microcks-ingress-secret") }}
  rules:
  - host: "{{ .Values.microcks.url }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.appName }}"
            port:
              number: 8080
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Values.appName }}-grpc"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  {{- with .Values.microcks.grpcIngressAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: "{{ .Values.appName }}"
    group: microcks
spec:
  tls:
  - hosts:
     - {{ ( include "microcks-grpc.url" . ) }}
  rules:
  - host: {{ ( include "microcks-grpc.url" . ) }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.appName }}-grpc"
            port:
              number: 9090
{{- if .Values.keycloak.install }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Values.appName }}-keycloak"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  {{- with .Values.keycloak.ingressAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: "{{ .Values.appName }}"
    group: microcks
spec:
  tls:
  - hosts:
    - "{{ .Values.keycloak.url }}"
    secretName: {{ .Values.keycloak.ingressSecretRef | default (print .Values.appName "-keycloak-ingress-secret") }}
  rules:
  - host: "{{ .Values.keycloak.url }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.appName }}-keycloak"
            port:
              number: 8080
{{- end }}
{{- if and .Values.features.async.enabled }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Values.appName }}-ws"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3000"
  {{- with .Values.features.async.ws.ingressAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: "{{ .Values.appName }}"
    group: microcks
spec:
  tls:
  - hosts:
    - "{{ ( include "microcks-ws.url" . ) }}"
    secretName: {{ .Values.features.async.ws.ingressSecretRef | default (print .Values.appName "-microcks-ws-ingress-secret") }}
  rules:
  - host: "{{ ( include "microcks-ws.url" . ) }}"
    http:
      paths:
        - path: /api/ws
          pathType: Prefix
          backend:
            service:
              name: "{{ .Values.appName }}-async-minion"
              port:
                number: 8080
{{- end }}
{{- end -}}
```
