### ISSUE TITLE
Intermittent UI problem with service loading (probably network latency).

### ISSUE THREAD

**Issue by jlozano-rh** [microcks/microcks#882]
### Describe the bug

I installed Microcks on an OpenShift 4.10.16 cluster and connected it to a Red Hat Single Sign-On 7.4 (Keycloak 9) and configured it properly.

But I'm connected to the cluster (and Microcks) remotely via VPN. Here is a brief description of the current situation:
![architecture](https://i.ibb.co/WBLC6HW/microcks-architecture.png)

The problem occurs when I click on the "APIs | Services" section where (after having imported a service contract) sometimes the interface does not load the list of available APIs, forcing me to refresh the page. This behavior is random, sometimes it occurs and sometimes it does not.

### Expected behavior

When I click on the "APIs | Services" section I should be able to see a list of the available APIs (previously imported) but this does not happen.

### Actual behavior

When I click on the "APIs | Services" section I'm sometimes able to see the list of available APIs and sometimes not.

### How to Reproduce?

Steps:

1.  Open microcks and login into the platform with **admin** user
2. Click on "Importers" section and import the following service: `https://raw.githubusercontent.com/lbroudoux/apicurio-test/master/mocks/Beer%20Catalog%20API.postman_collection.json` 
3. Click on options (3 vertical dots) and force import.
4. Click on "APIs | Services" section and see the available API
5. Click on another section, and clicl on "APIs | Services" section again to see the list of available APIs

PS: repeat steps 4 and 5... sometimes the list appears and sometimes not.

### Microcks version or git rev

1.7.1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

operator

### Additional information

I've used next CRD to instantiate Microcks:
```yaml
apiVersion: microcks.github.io/v1alpha1 
kind: MicrocksInstall 
metadata: 
  name: microcks 
  namespace: tooling 
spec: 
  name: microcks 
  version: 1.7.1 
  microcks: 
    replicas: 1 
  postman: 
    replicas: 1 
  keycloak: 
    install: false 
    privateUrl: 'https://<rhsso-keycloak_URL>/auth' 
    realm: microcks 
    serviceAccount: microcks-serviceaccount 
    serviceAccountCredentials: abcdefg-1234-xxxx-xxxx-xxxxxxxxxx 
    url: '<rhsso-keycloak_URL>'
  mongodb: 
    install: true 
    persistent: true 
    volumeSize: 2Gi 
```
