### ISSUE TITLE
Accept external lib in groovy script

### ISSUE THREAD

**Issue by sfraigneau** [microcks/microcks#897]
### Reason/Context

We want to use external lib in our groovy script

### Description

We coulp provide to microcks a path where our libs belong (jar files)

**Comment by lbroudoux** [comment]
Done some tests on this, and it's already possible 😉 Just a matter of writing a nice documentation or blog post...

To give you quickly the raw directions: there are 2 approaches depending if you use docker-compose or pure Kubernetes installation.

#### docker-compose method

1. Put your Jar files into a `./lib` folder
2. Add the following lines into your compose file for the Microcks container:
```yaml
   volumes:
      - ./lib:/deployments/lib
    environment:
      - JAVA_OPTIONS=-Dloader.path=/deployments/lib
      - JAVA_MAIN_CLASS=org.springframework.boot.loader.PropertiesLauncher
      - JAVA_APP_JAR=app.jar
```
3. Restart and see the Jar files appended to the application classpath.
4. You can directly use the Java or Groovy classes from your Jar in a `SCRIPT`

#### Pure Kubernetes method

1. Put your Jar files into a local `./lib` folder
2. Create a new Docker file that extends the Microcks provided image and embeds your libs
```yaml
FROM quay.io/microcks/microcks-uber:nightly

# Copy libraries jar files
COPY lib /deployments/lib

ENV JAVA_OPTIONS=-Dloader.path=/deployments/lib
ENV JAVA_MAIN_CLASS=org.springframework.boot.loader.PropertiesLauncher
ENV JAVA_APP_JAR=app.jar
```
3. Restart and see the Jar files appended to the application classpath.
4. You can directly use the Java or Groovy classes from your Jar in a `SCRIPT`

Let me know if it helps!
