### ISSUE TITLE
Helm chart does not deploy mongodb connection secret when generateCert value is set to false

### ISSUE THREAD

**Issue by tristansavina** [microcks/microcks#910]
### Describe the bug

Some conditions related to ssl certificate are linked to the condition of deployment of secret for mongo connection, due to a misplaced {{ - end }} tag

the "if" condition : https://github.com/microcks/microcks/blob/5f64edfa54727c0c2490cf8f965dc6dcbec67697/install/kubernetes/microcks/templates/secret.yaml#L11

### Expected behavior

when mongodb.install==true, I expect to have a secret created to connect to my mongo cluster

### Actual behavior

A secret will not be created when microcks.generateCert==false

### How to Reproduce?

With this configuration in Values.yaml :

```yaml
appName: microcks
ingresses: true

mongodb:
  install: true

microcks:
  #ingressSecretRef: not_used
  generateCert: false
```

Log secrets that should be set
```sh
helm install lizard-microcks-test ./ --namespace testmicrocks --dry-run --debug
```

  

### Microcks version or git rev

5f64edfa54727c0c2490cf8f965dc6dcbec67697

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

helm chart
